-- jev_kuramoto_tb.vhd -- self-checking testbench generated by the WASMApollo EDA; the expected
-- values are the fabric's golden model (RefSim). Run: ghdl -a jev_kuramoto.vhd jev_kuramoto_tb.vhd && ghdl -e jev_kuramoto_tb && ghdl -r jev_kuramoto_tb

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity jev_kuramoto_tb is
end entity jev_kuramoto_tb;

architecture sim of jev_kuramoto_tb is
  signal clk : std_logic := '0';
  signal rst : std_logic := '1';
  signal finished : boolean := false;
  signal src0 : std_logic := '0';
  signal src1 : std_logic := '0';
  signal src2 : std_logic := '0';
  signal src3 : std_logic := '0';
  signal src_en : std_logic_vector(3 downto 0) := (others => '0');
  signal omega_we : std_logic := '0';
  signal omega_d : unsigned(31 downto 0) := (others => '0');
  signal phase_out : unsigned(31 downto 0);
  signal freq_out : unsigned(31 downto 0);
  signal wrap : std_logic_vector(3 downto 0);
  signal near : std_logic_vector(5 downto 0);
  signal fault : std_logic_vector(3 downto 0);
  signal lost : std_logic_vector(3 downto 0);
  signal locked : std_logic_vector(3 downto 0);
  signal glitch : std_logic_vector(3 downto 0);
  signal coherent : std_logic;
  signal quorum : std_logic;
  signal ec_tick : std_logic;
  signal status : std_logic_vector(3 downto 0);
begin
  dut : entity work.jev_kuramoto port map (clk => clk, rst => rst, src0 => src0, src1 => src1, src2 => src2, src3 => src3, src_en => src_en, omega_we => omega_we, omega_d => omega_d, phase_out => phase_out, freq_out => freq_out, wrap => wrap, near => near, fault => fault, lost => lost, locked => locked, glitch => glitch, coherent => coherent, quorum => quorum, ec_tick => ec_tick, status => status);
  clk <= not clk after 5 ns when not finished else '0';

  check : process
    variable errors : natural := 0;
    procedure tick is
    begin
      wait until rising_edge(clk);
      wait for 1 ns;
    end procedure;
  begin
    -- vector 0
    src0 <= '1';
    src1 <= '1';
    src2 <= '1';
    src3 <= '1';
    src_en <= "1010";
    omega_we <= '1';
    omega_d <= x"0EB6DF69";
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 64 loop
      tick;
    end loop;
    if phase_out /= x"98F7BCDD" then
      report "FAIL vector 0: phase_out" severity error;
      errors := errors + 1;
    end if;
    if freq_out /= x"0EB6DF69" then
      report "FAIL vector 0: freq_out" severity error;
      errors := errors + 1;
    end if;
    if wrap /= "0000" then
      report "FAIL vector 0: wrap" severity error;
      errors := errors + 1;
    end if;
    if near /= "111111" then
      report "FAIL vector 0: near" severity error;
      errors := errors + 1;
    end if;
    if fault /= "0000" then
      report "FAIL vector 0: fault" severity error;
      errors := errors + 1;
    end if;
    if lost /= "0000" then
      report "FAIL vector 0: lost" severity error;
      errors := errors + 1;
    end if;
    if locked /= "0000" then
      report "FAIL vector 0: locked" severity error;
      errors := errors + 1;
    end if;
    if glitch /= "0000" then
      report "FAIL vector 0: glitch" severity error;
      errors := errors + 1;
    end if;
    if coherent /= '1' then
      report "FAIL vector 0: coherent" severity error;
      errors := errors + 1;
    end if;
    if quorum /= '1' then
      report "FAIL vector 0: quorum" severity error;
      errors := errors + 1;
    end if;
    if ec_tick /= '0' then
      report "FAIL vector 0: ec_tick" severity error;
      errors := errors + 1;
    end if;
    if status /= "0001" then
      report "FAIL vector 0: status" severity error;
      errors := errors + 1;
    end if;
    -- vector 1
    src0 <= '1';
    src1 <= '1';
    src2 <= '1';
    src3 <= '1';
    src_en <= "1100";
    omega_we <= '0';
    omega_d <= x"115E6AD2";
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 64 loop
      tick;
    end loop;
    if phase_out /= x"08706CDC" then
      report "FAIL vector 1: phase_out" severity error;
      errors := errors + 1;
    end if;
    if freq_out /= x"105220B5" then
      report "FAIL vector 1: freq_out" severity error;
      errors := errors + 1;
    end if;
    if wrap /= "1111" then
      report "FAIL vector 1: wrap" severity error;
      errors := errors + 1;
    end if;
    if near /= "111111" then
      report "FAIL vector 1: near" severity error;
      errors := errors + 1;
    end if;
    if fault /= "0000" then
      report "FAIL vector 1: fault" severity error;
      errors := errors + 1;
    end if;
    if lost /= "0000" then
      report "FAIL vector 1: lost" severity error;
      errors := errors + 1;
    end if;
    if locked /= "0000" then
      report "FAIL vector 1: locked" severity error;
      errors := errors + 1;
    end if;
    if glitch /= "0000" then
      report "FAIL vector 1: glitch" severity error;
      errors := errors + 1;
    end if;
    if coherent /= '1' then
      report "FAIL vector 1: coherent" severity error;
      errors := errors + 1;
    end if;
    if quorum /= '1' then
      report "FAIL vector 1: quorum" severity error;
      errors := errors + 1;
    end if;
    if ec_tick /= '1' then
      report "FAIL vector 1: ec_tick" severity error;
      errors := errors + 1;
    end if;
    if status /= "0001" then
      report "FAIL vector 1: status" severity error;
      errors := errors + 1;
    end if;
    -- vector 2
    src0 <= '0';
    src1 <= '1';
    src2 <= '0';
    src3 <= '0';
    src_en <= "1001";
    omega_we <= '0';
    omega_d <= x"1183105D";
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 64 loop
      tick;
    end loop;
    if phase_out /= x"05C1D195" then
      report "FAIL vector 2: phase_out" severity error;
      errors := errors + 1;
    end if;
    if freq_out /= x"105150D0" then
      report "FAIL vector 2: freq_out" severity error;
      errors := errors + 1;
    end if;
    if wrap /= "1111" then
      report "FAIL vector 2: wrap" severity error;
      errors := errors + 1;
    end if;
    if near /= "111111" then
      report "FAIL vector 2: near" severity error;
      errors := errors + 1;
    end if;
    if fault /= "0000" then
      report "FAIL vector 2: fault" severity error;
      errors := errors + 1;
    end if;
    if lost /= "0000" then
      report "FAIL vector 2: lost" severity error;
      errors := errors + 1;
    end if;
    if locked /= "0000" then
      report "FAIL vector 2: locked" severity error;
      errors := errors + 1;
    end if;
    if glitch /= "0000" then
      report "FAIL vector 2: glitch" severity error;
      errors := errors + 1;
    end if;
    if coherent /= '1' then
      report "FAIL vector 2: coherent" severity error;
      errors := errors + 1;
    end if;
    if quorum /= '1' then
      report "FAIL vector 2: quorum" severity error;
      errors := errors + 1;
    end if;
    if ec_tick /= '1' then
      report "FAIL vector 2: ec_tick" severity error;
      errors := errors + 1;
    end if;
    if status /= "0001" then
      report "FAIL vector 2: status" severity error;
      errors := errors + 1;
    end if;
    -- vector 3
    src0 <= '0';
    src1 <= '0';
    src2 <= '0';
    src3 <= '0';
    src_en <= "0011";
    omega_we <= '0';
    omega_d <= x"10B5EB4F";
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 64 loop
      tick;
    end loop;
    if phase_out /= x"05C1D195" then
      report "FAIL vector 3: phase_out" severity error;
      errors := errors + 1;
    end if;
    if freq_out /= x"105150D0" then
      report "FAIL vector 3: freq_out" severity error;
      errors := errors + 1;
    end if;
    if wrap /= "1111" then
      report "FAIL vector 3: wrap" severity error;
      errors := errors + 1;
    end if;
    if near /= "111111" then
      report "FAIL vector 3: near" severity error;
      errors := errors + 1;
    end if;
    if fault /= "0000" then
      report "FAIL vector 3: fault" severity error;
      errors := errors + 1;
    end if;
    if lost /= "0000" then
      report "FAIL vector 3: lost" severity error;
      errors := errors + 1;
    end if;
    if locked /= "0000" then
      report "FAIL vector 3: locked" severity error;
      errors := errors + 1;
    end if;
    if glitch /= "0000" then
      report "FAIL vector 3: glitch" severity error;
      errors := errors + 1;
    end if;
    if coherent /= '1' then
      report "FAIL vector 3: coherent" severity error;
      errors := errors + 1;
    end if;
    if quorum /= '1' then
      report "FAIL vector 3: quorum" severity error;
      errors := errors + 1;
    end if;
    if ec_tick /= '1' then
      report "FAIL vector 3: ec_tick" severity error;
      errors := errors + 1;
    end if;
    if status /= "0001" then
      report "FAIL vector 3: status" severity error;
      errors := errors + 1;
    end if;
    -- vector 4
    src0 <= '0';
    src1 <= '1';
    src2 <= '1';
    src3 <= '1';
    src_en <= "1101";
    omega_we <= '0';
    omega_d <= x"0EDBD022";
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 64 loop
      tick;
    end loop;
    if phase_out /= x"08706CDC" then
      report "FAIL vector 4: phase_out" severity error;
      errors := errors + 1;
    end if;
    if freq_out /= x"105220B5" then
      report "FAIL vector 4: freq_out" severity error;
      errors := errors + 1;
    end if;
    if wrap /= "1111" then
      report "FAIL vector 4: wrap" severity error;
      errors := errors + 1;
    end if;
    if near /= "111111" then
      report "FAIL vector 4: near" severity error;
      errors := errors + 1;
    end if;
    if fault /= "0000" then
      report "FAIL vector 4: fault" severity error;
      errors := errors + 1;
    end if;
    if lost /= "0000" then
      report "FAIL vector 4: lost" severity error;
      errors := errors + 1;
    end if;
    if locked /= "0000" then
      report "FAIL vector 4: locked" severity error;
      errors := errors + 1;
    end if;
    if glitch /= "0000" then
      report "FAIL vector 4: glitch" severity error;
      errors := errors + 1;
    end if;
    if coherent /= '1' then
      report "FAIL vector 4: coherent" severity error;
      errors := errors + 1;
    end if;
    if quorum /= '1' then
      report "FAIL vector 4: quorum" severity error;
      errors := errors + 1;
    end if;
    if ec_tick /= '1' then
      report "FAIL vector 4: ec_tick" severity error;
      errors := errors + 1;
    end if;
    if status /= "0001" then
      report "FAIL vector 4: status" severity error;
      errors := errors + 1;
    end if;
    -- vector 5
    src0 <= '1';
    src1 <= '0';
    src2 <= '0';
    src3 <= '1';
    src_en <= "0011";
    omega_we <= '0';
    omega_d <= x"1007B4DE";
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 64 loop
      tick;
    end loop;
    if phase_out /= x"0A1E5D65" then
      report "FAIL vector 5: phase_out" severity error;
      errors := errors + 1;
    end if;
    if freq_out /= x"106BDC49" then
      report "FAIL vector 5: freq_out" severity error;
      errors := errors + 1;
    end if;
    if wrap /= "1111" then
      report "FAIL vector 5: wrap" severity error;
      errors := errors + 1;
    end if;
    if near /= "111111" then
      report "FAIL vector 5: near" severity error;
      errors := errors + 1;
    end if;
    if fault /= "0000" then
      report "FAIL vector 5: fault" severity error;
      errors := errors + 1;
    end if;
    if lost /= "0000" then
      report "FAIL vector 5: lost" severity error;
      errors := errors + 1;
    end if;
    if locked /= "0000" then
      report "FAIL vector 5: locked" severity error;
      errors := errors + 1;
    end if;
    if glitch /= "0000" then
      report "FAIL vector 5: glitch" severity error;
      errors := errors + 1;
    end if;
    if coherent /= '1' then
      report "FAIL vector 5: coherent" severity error;
      errors := errors + 1;
    end if;
    if quorum /= '1' then
      report "FAIL vector 5: quorum" severity error;
      errors := errors + 1;
    end if;
    if ec_tick /= '1' then
      report "FAIL vector 5: ec_tick" severity error;
      errors := errors + 1;
    end if;
    if status /= "0001" then
      report "FAIL vector 5: status" severity error;
      errors := errors + 1;
    end if;
    -- vector 6
    src0 <= '1';
    src1 <= '0';
    src2 <= '0';
    src3 <= '1';
    src_en <= "1011";
    omega_we <= '1';
    omega_d <= x"0E235DD0";
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 64 loop
      tick;
    end loop;
    if phase_out /= x"779EF438" then
      report "FAIL vector 6: phase_out" severity error;
      errors := errors + 1;
    end if;
    if freq_out /= x"0E235DD0" then
      report "FAIL vector 6: freq_out" severity error;
      errors := errors + 1;
    end if;
    if wrap /= "0000" then
      report "FAIL vector 6: wrap" severity error;
      errors := errors + 1;
    end if;
    if near /= "111111" then
      report "FAIL vector 6: near" severity error;
      errors := errors + 1;
    end if;
    if fault /= "0000" then
      report "FAIL vector 6: fault" severity error;
      errors := errors + 1;
    end if;
    if lost /= "0000" then
      report "FAIL vector 6: lost" severity error;
      errors := errors + 1;
    end if;
    if locked /= "0000" then
      report "FAIL vector 6: locked" severity error;
      errors := errors + 1;
    end if;
    if glitch /= "0000" then
      report "FAIL vector 6: glitch" severity error;
      errors := errors + 1;
    end if;
    if coherent /= '1' then
      report "FAIL vector 6: coherent" severity error;
      errors := errors + 1;
    end if;
    if quorum /= '1' then
      report "FAIL vector 6: quorum" severity error;
      errors := errors + 1;
    end if;
    if ec_tick /= '0' then
      report "FAIL vector 6: ec_tick" severity error;
      errors := errors + 1;
    end if;
    if status /= "0001" then
      report "FAIL vector 6: status" severity error;
      errors := errors + 1;
    end if;
    -- vector 7
    src0 <= '0';
    src1 <= '1';
    src2 <= '1';
    src3 <= '1';
    src_en <= "0101";
    omega_we <= '0';
    omega_d <= x"0E8B5843";
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 64 loop
      tick;
    end loop;
    if phase_out /= x"0AA96923" then
      report "FAIL vector 7: phase_out" severity error;
      errors := errors + 1;
    end if;
    if freq_out /= x"1056C28A" then
      report "FAIL vector 7: freq_out" severity error;
      errors := errors + 1;
    end if;
    if wrap /= "1111" then
      report "FAIL vector 7: wrap" severity error;
      errors := errors + 1;
    end if;
    if near /= "111111" then
      report "FAIL vector 7: near" severity error;
      errors := errors + 1;
    end if;
    if fault /= "0000" then
      report "FAIL vector 7: fault" severity error;
      errors := errors + 1;
    end if;
    if lost /= "0000" then
      report "FAIL vector 7: lost" severity error;
      errors := errors + 1;
    end if;
    if locked /= "0000" then
      report "FAIL vector 7: locked" severity error;
      errors := errors + 1;
    end if;
    if glitch /= "0000" then
      report "FAIL vector 7: glitch" severity error;
      errors := errors + 1;
    end if;
    if coherent /= '1' then
      report "FAIL vector 7: coherent" severity error;
      errors := errors + 1;
    end if;
    if quorum /= '1' then
      report "FAIL vector 7: quorum" severity error;
      errors := errors + 1;
    end if;
    if ec_tick /= '1' then
      report "FAIL vector 7: ec_tick" severity error;
      errors := errors + 1;
    end if;
    if status /= "0001" then
      report "FAIL vector 7: status" severity error;
      errors := errors + 1;
    end if;
    -- vector 8
    src0 <= '0';
    src1 <= '0';
    src2 <= '0';
    src3 <= '1';
    src_en <= "0011";
    omega_we <= '0';
    omega_d <= x"105ED74E";
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 64 loop
      tick;
    end loop;
    if phase_out /= x"05C1D195" then
      report "FAIL vector 8: phase_out" severity error;
      errors := errors + 1;
    end if;
    if freq_out /= x"105150D0" then
      report "FAIL vector 8: freq_out" severity error;
      errors := errors + 1;
    end if;
    if wrap /= "1111" then
      report "FAIL vector 8: wrap" severity error;
      errors := errors + 1;
    end if;
    if near /= "111111" then
      report "FAIL vector 8: near" severity error;
      errors := errors + 1;
    end if;
    if fault /= "0000" then
      report "FAIL vector 8: fault" severity error;
      errors := errors + 1;
    end if;
    if lost /= "0000" then
      report "FAIL vector 8: lost" severity error;
      errors := errors + 1;
    end if;
    if locked /= "0000" then
      report "FAIL vector 8: locked" severity error;
      errors := errors + 1;
    end if;
    if glitch /= "0000" then
      report "FAIL vector 8: glitch" severity error;
      errors := errors + 1;
    end if;
    if coherent /= '1' then
      report "FAIL vector 8: coherent" severity error;
      errors := errors + 1;
    end if;
    if quorum /= '1' then
      report "FAIL vector 8: quorum" severity error;
      errors := errors + 1;
    end if;
    if ec_tick /= '1' then
      report "FAIL vector 8: ec_tick" severity error;
      errors := errors + 1;
    end if;
    if status /= "0001" then
      report "FAIL vector 8: status" severity error;
      errors := errors + 1;
    end if;
    -- vector 9
    src0 <= '0';
    src1 <= '0';
    src2 <= '0';
    src3 <= '1';
    src_en <= "1000";
    omega_we <= '0';
    omega_d <= x"112F704E";
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 64 loop
      tick;
    end loop;
    if phase_out /= x"039B0265" then
      report "FAIL vector 9: phase_out" severity error;
      errors := errors + 1;
    end if;
    if freq_out /= x"104CEE6E" then
      report "FAIL vector 9: freq_out" severity error;
      errors := errors + 1;
    end if;
    if wrap /= "1111" then
      report "FAIL vector 9: wrap" severity error;
      errors := errors + 1;
    end if;
    if near /= "111111" then
      report "FAIL vector 9: near" severity error;
      errors := errors + 1;
    end if;
    if fault /= "0000" then
      report "FAIL vector 9: fault" severity error;
      errors := errors + 1;
    end if;
    if lost /= "0000" then
      report "FAIL vector 9: lost" severity error;
      errors := errors + 1;
    end if;
    if locked /= "0000" then
      report "FAIL vector 9: locked" severity error;
      errors := errors + 1;
    end if;
    if glitch /= "0000" then
      report "FAIL vector 9: glitch" severity error;
      errors := errors + 1;
    end if;
    if coherent /= '1' then
      report "FAIL vector 9: coherent" severity error;
      errors := errors + 1;
    end if;
    if quorum /= '1' then
      report "FAIL vector 9: quorum" severity error;
      errors := errors + 1;
    end if;
    if ec_tick /= '1' then
      report "FAIL vector 9: ec_tick" severity error;
      errors := errors + 1;
    end if;
    if status /= "0001" then
      report "FAIL vector 9: status" severity error;
      errors := errors + 1;
    end if;
    -- vector 10
    src0 <= '0';
    src1 <= '1';
    src2 <= '1';
    src3 <= '0';
    src_en <= "1011";
    omega_we <= '0';
    omega_d <= x"102006CF";
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 64 loop
      tick;
    end loop;
    if phase_out /= x"FDAD532C" then
      report "FAIL vector 10: phase_out" severity error;
      errors := errors + 1;
    end if;
    if freq_out /= x"1046B862" then
      report "FAIL vector 10: freq_out" severity error;
      errors := errors + 1;
    end if;
    if wrap /= "0000" then
      report "FAIL vector 10: wrap" severity error;
      errors := errors + 1;
    end if;
    if near /= "111111" then
      report "FAIL vector 10: near" severity error;
      errors := errors + 1;
    end if;
    if fault /= "0000" then
      report "FAIL vector 10: fault" severity error;
      errors := errors + 1;
    end if;
    if lost /= "0000" then
      report "FAIL vector 10: lost" severity error;
      errors := errors + 1;
    end if;
    if locked /= "0000" then
      report "FAIL vector 10: locked" severity error;
      errors := errors + 1;
    end if;
    if glitch /= "0000" then
      report "FAIL vector 10: glitch" severity error;
      errors := errors + 1;
    end if;
    if coherent /= '1' then
      report "FAIL vector 10: coherent" severity error;
      errors := errors + 1;
    end if;
    if quorum /= '1' then
      report "FAIL vector 10: quorum" severity error;
      errors := errors + 1;
    end if;
    if ec_tick /= '0' then
      report "FAIL vector 10: ec_tick" severity error;
      errors := errors + 1;
    end if;
    if status /= "0001" then
      report "FAIL vector 10: status" severity error;
      errors := errors + 1;
    end if;
    -- vector 11
    src0 <= '0';
    src1 <= '0';
    src2 <= '1';
    src3 <= '0';
    src_en <= "1110";
    omega_we <= '0';
    omega_d <= x"101724B2";
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 64 loop
      tick;
    end loop;
    if phase_out /= x"0AA96923" then
      report "FAIL vector 11: phase_out" severity error;
      errors := errors + 1;
    end if;
    if freq_out /= x"1056C28A" then
      report "FAIL vector 11: freq_out" severity error;
      errors := errors + 1;
    end if;
    if wrap /= "1111" then
      report "FAIL vector 11: wrap" severity error;
      errors := errors + 1;
    end if;
    if near /= "111111" then
      report "FAIL vector 11: near" severity error;
      errors := errors + 1;
    end if;
    if fault /= "0000" then
      report "FAIL vector 11: fault" severity error;
      errors := errors + 1;
    end if;
    if lost /= "0000" then
      report "FAIL vector 11: lost" severity error;
      errors := errors + 1;
    end if;
    if locked /= "0000" then
      report "FAIL vector 11: locked" severity error;
      errors := errors + 1;
    end if;
    if glitch /= "0000" then
      report "FAIL vector 11: glitch" severity error;
      errors := errors + 1;
    end if;
    if coherent /= '1' then
      report "FAIL vector 11: coherent" severity error;
      errors := errors + 1;
    end if;
    if quorum /= '1' then
      report "FAIL vector 11: quorum" severity error;
      errors := errors + 1;
    end if;
    if ec_tick /= '1' then
      report "FAIL vector 11: ec_tick" severity error;
      errors := errors + 1;
    end if;
    if status /= "0001" then
      report "FAIL vector 11: status" severity error;
      errors := errors + 1;
    end if;
    -- vector 12
    src0 <= '1';
    src1 <= '0';
    src2 <= '0';
    src3 <= '0';
    src_en <= "0101";
    omega_we <= '1';
    omega_d <= x"0FF3117D";
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 64 loop
      tick;
    end loop;
    if phase_out /= x"EB79DE68" then
      report "FAIL vector 12: phase_out" severity error;
      errors := errors + 1;
    end if;
    if freq_out /= x"0FF3117D" then
      report "FAIL vector 12: freq_out" severity error;
      errors := errors + 1;
    end if;
    if wrap /= "0000" then
      report "FAIL vector 12: wrap" severity error;
      errors := errors + 1;
    end if;
    if near /= "111111" then
      report "FAIL vector 12: near" severity error;
      errors := errors + 1;
    end if;
    if fault /= "0000" then
      report "FAIL vector 12: fault" severity error;
      errors := errors + 1;
    end if;
    if lost /= "0000" then
      report "FAIL vector 12: lost" severity error;
      errors := errors + 1;
    end if;
    if locked /= "0000" then
      report "FAIL vector 12: locked" severity error;
      errors := errors + 1;
    end if;
    if glitch /= "0000" then
      report "FAIL vector 12: glitch" severity error;
      errors := errors + 1;
    end if;
    if coherent /= '1' then
      report "FAIL vector 12: coherent" severity error;
      errors := errors + 1;
    end if;
    if quorum /= '1' then
      report "FAIL vector 12: quorum" severity error;
      errors := errors + 1;
    end if;
    if ec_tick /= '0' then
      report "FAIL vector 12: ec_tick" severity error;
      errors := errors + 1;
    end if;
    if status /= "0001" then
      report "FAIL vector 12: status" severity error;
      errors := errors + 1;
    end if;
    -- vector 13
    src0 <= '0';
    src1 <= '0';
    src2 <= '0';
    src3 <= '1';
    src_en <= "0110";
    omega_we <= '0';
    omega_d <= x"108FFF57";
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 64 loop
      tick;
    end loop;
    if phase_out /= x"05C1D195" then
      report "FAIL vector 13: phase_out" severity error;
      errors := errors + 1;
    end if;
    if freq_out /= x"105150D0" then
      report "FAIL vector 13: freq_out" severity error;
      errors := errors + 1;
    end if;
    if wrap /= "1111" then
      report "FAIL vector 13: wrap" severity error;
      errors := errors + 1;
    end if;
    if near /= "111111" then
      report "FAIL vector 13: near" severity error;
      errors := errors + 1;
    end if;
    if fault /= "0000" then
      report "FAIL vector 13: fault" severity error;
      errors := errors + 1;
    end if;
    if lost /= "0000" then
      report "FAIL vector 13: lost" severity error;
      errors := errors + 1;
    end if;
    if locked /= "0000" then
      report "FAIL vector 13: locked" severity error;
      errors := errors + 1;
    end if;
    if glitch /= "0000" then
      report "FAIL vector 13: glitch" severity error;
      errors := errors + 1;
    end if;
    if coherent /= '1' then
      report "FAIL vector 13: coherent" severity error;
      errors := errors + 1;
    end if;
    if quorum /= '1' then
      report "FAIL vector 13: quorum" severity error;
      errors := errors + 1;
    end if;
    if ec_tick /= '1' then
      report "FAIL vector 13: ec_tick" severity error;
      errors := errors + 1;
    end if;
    if status /= "0001" then
      report "FAIL vector 13: status" severity error;
      errors := errors + 1;
    end if;
    -- vector 14
    src0 <= '1';
    src1 <= '1';
    src2 <= '0';
    src3 <= '0';
    src_en <= "0000";
    omega_we <= '0';
    omega_d <= x"0EBD80A0";
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 64 loop
      tick;
    end loop;
    if phase_out /= x"05C1D195" then
      report "FAIL vector 14: phase_out" severity error;
      errors := errors + 1;
    end if;
    if freq_out /= x"105150D0" then
      report "FAIL vector 14: freq_out" severity error;
      errors := errors + 1;
    end if;
    if wrap /= "1111" then
      report "FAIL vector 14: wrap" severity error;
      errors := errors + 1;
    end if;
    if near /= "111111" then
      report "FAIL vector 14: near" severity error;
      errors := errors + 1;
    end if;
    if fault /= "0000" then
      report "FAIL vector 14: fault" severity error;
      errors := errors + 1;
    end if;
    if lost /= "0000" then
      report "FAIL vector 14: lost" severity error;
      errors := errors + 1;
    end if;
    if locked /= "0000" then
      report "FAIL vector 14: locked" severity error;
      errors := errors + 1;
    end if;
    if glitch /= "0000" then
      report "FAIL vector 14: glitch" severity error;
      errors := errors + 1;
    end if;
    if coherent /= '1' then
      report "FAIL vector 14: coherent" severity error;
      errors := errors + 1;
    end if;
    if quorum /= '1' then
      report "FAIL vector 14: quorum" severity error;
      errors := errors + 1;
    end if;
    if ec_tick /= '1' then
      report "FAIL vector 14: ec_tick" severity error;
      errors := errors + 1;
    end if;
    if status /= "0001" then
      report "FAIL vector 14: status" severity error;
      errors := errors + 1;
    end if;
    -- vector 15
    src0 <= '1';
    src1 <= '0';
    src2 <= '1';
    src3 <= '1';
    src_en <= "0011";
    omega_we <= '0';
    omega_d <= x"0F1F1D27";
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 64 loop
      tick;
    end loop;
    if phase_out /= x"0A1E5D65" then
      report "FAIL vector 15: phase_out" severity error;
      errors := errors + 1;
    end if;
    if freq_out /= x"106BDC49" then
      report "FAIL vector 15: freq_out" severity error;
      errors := errors + 1;
    end if;
    if wrap /= "1111" then
      report "FAIL vector 15: wrap" severity error;
      errors := errors + 1;
    end if;
    if near /= "111111" then
      report "FAIL vector 15: near" severity error;
      errors := errors + 1;
    end if;
    if fault /= "0000" then
      report "FAIL vector 15: fault" severity error;
      errors := errors + 1;
    end if;
    if lost /= "0000" then
      report "FAIL vector 15: lost" severity error;
      errors := errors + 1;
    end if;
    if locked /= "0000" then
      report "FAIL vector 15: locked" severity error;
      errors := errors + 1;
    end if;
    if glitch /= "0000" then
      report "FAIL vector 15: glitch" severity error;
      errors := errors + 1;
    end if;
    if coherent /= '1' then
      report "FAIL vector 15: coherent" severity error;
      errors := errors + 1;
    end if;
    if quorum /= '1' then
      report "FAIL vector 15: quorum" severity error;
      errors := errors + 1;
    end if;
    if ec_tick /= '1' then
      report "FAIL vector 15: ec_tick" severity error;
      errors := errors + 1;
    end if;
    if status /= "0001" then
      report "FAIL vector 15: status" severity error;
      errors := errors + 1;
    end if;
    if errors = 0 then
      report "PASS jev_kuramoto: 16 vectors";
    else
      report "FAIL jev_kuramoto: " & integer'image(errors) & " mismatches" severity failure;
    end if;
    finished <= true;
    wait;
  end process;
end architecture sim;
