`timescale 1ns/1ps
// jev_kuramoto_tb.v -- self-checking testbench generated by the WASMApollo EDA; the expected
// values are the fabric's golden model (RefSim). Run: iverilog -o tb jev_kuramoto.v jev_kuramoto_tb.v && vvp tb

module jev_kuramoto_tb;
  reg clk = 1'b0;
  reg rst = 1'b1;
  reg src0 = 0;
  reg src1 = 0;
  reg src2 = 0;
  reg src3 = 0;
  reg [3:0] src_en = 0;
  reg omega_we = 0;
  reg [31:0] omega_d = 0;
  wire [31:0] phase_out;
  wire [31:0] freq_out;
  wire [3:0] wrap;
  wire [5:0] near;
  wire [3:0] fault;
  wire [3:0] lost;
  wire [3:0] locked;
  wire [3:0] glitch;
  wire coherent;
  wire quorum;
  wire ec_tick;
  wire [3:0] status;
  integer errors = 0;

  jev_kuramoto dut (.clk(clk), .rst(rst), .src0(src0), .src1(src1), .src2(src2), .src3(src3), .src_en(src_en), .omega_we(omega_we), .omega_d(omega_d), .phase_out(phase_out), .freq_out(freq_out), .wrap(wrap), .near(near), .fault(fault), .lost(lost), .locked(locked), .glitch(glitch), .coherent(coherent), .quorum(quorum), .ec_tick(ec_tick), .status(status));

  always #5 clk = ~clk;
  task tick;
    begin
      @(posedge clk);
      #1;
    end
  endtask

  initial begin
    // vector 0
    src0 = 1'h1;
    src1 = 1'h1;
    src2 = 1'h1;
    src3 = 1'h1;
    src_en = 4'hA;
    omega_we = 1'h1;
    omega_d = 32'h0EB6DF69;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (64) tick;
    if (phase_out !== 32'h98F7BCDD) begin $display("FAIL vector 0: phase_out = %h, want %h", phase_out, 32'h98F7BCDD); errors = errors + 1; end
    if (freq_out !== 32'h0EB6DF69) begin $display("FAIL vector 0: freq_out = %h, want %h", freq_out, 32'h0EB6DF69); errors = errors + 1; end
    if (wrap !== 4'h0) begin $display("FAIL vector 0: wrap = %h, want %h", wrap, 4'h0); errors = errors + 1; end
    if (near !== 6'h3F) begin $display("FAIL vector 0: near = %h, want %h", near, 6'h3F); errors = errors + 1; end
    if (fault !== 4'h0) begin $display("FAIL vector 0: fault = %h, want %h", fault, 4'h0); errors = errors + 1; end
    if (lost !== 4'h0) begin $display("FAIL vector 0: lost = %h, want %h", lost, 4'h0); errors = errors + 1; end
    if (locked !== 4'h0) begin $display("FAIL vector 0: locked = %h, want %h", locked, 4'h0); errors = errors + 1; end
    if (glitch !== 4'h0) begin $display("FAIL vector 0: glitch = %h, want %h", glitch, 4'h0); errors = errors + 1; end
    if (coherent !== 1'h1) begin $display("FAIL vector 0: coherent = %h, want %h", coherent, 1'h1); errors = errors + 1; end
    if (quorum !== 1'h1) begin $display("FAIL vector 0: quorum = %h, want %h", quorum, 1'h1); errors = errors + 1; end
    if (ec_tick !== 1'h0) begin $display("FAIL vector 0: ec_tick = %h, want %h", ec_tick, 1'h0); errors = errors + 1; end
    if (status !== 4'h1) begin $display("FAIL vector 0: status = %h, want %h", status, 4'h1); errors = errors + 1; end
    // vector 1
    src0 = 1'h1;
    src1 = 1'h1;
    src2 = 1'h1;
    src3 = 1'h1;
    src_en = 4'hC;
    omega_we = 1'h0;
    omega_d = 32'h115E6AD2;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (64) tick;
    if (phase_out !== 32'h08706CDC) begin $display("FAIL vector 1: phase_out = %h, want %h", phase_out, 32'h08706CDC); errors = errors + 1; end
    if (freq_out !== 32'h105220B5) begin $display("FAIL vector 1: freq_out = %h, want %h", freq_out, 32'h105220B5); errors = errors + 1; end
    if (wrap !== 4'hF) begin $display("FAIL vector 1: wrap = %h, want %h", wrap, 4'hF); errors = errors + 1; end
    if (near !== 6'h3F) begin $display("FAIL vector 1: near = %h, want %h", near, 6'h3F); errors = errors + 1; end
    if (fault !== 4'h0) begin $display("FAIL vector 1: fault = %h, want %h", fault, 4'h0); errors = errors + 1; end
    if (lost !== 4'h0) begin $display("FAIL vector 1: lost = %h, want %h", lost, 4'h0); errors = errors + 1; end
    if (locked !== 4'h0) begin $display("FAIL vector 1: locked = %h, want %h", locked, 4'h0); errors = errors + 1; end
    if (glitch !== 4'h0) begin $display("FAIL vector 1: glitch = %h, want %h", glitch, 4'h0); errors = errors + 1; end
    if (coherent !== 1'h1) begin $display("FAIL vector 1: coherent = %h, want %h", coherent, 1'h1); errors = errors + 1; end
    if (quorum !== 1'h1) begin $display("FAIL vector 1: quorum = %h, want %h", quorum, 1'h1); errors = errors + 1; end
    if (ec_tick !== 1'h1) begin $display("FAIL vector 1: ec_tick = %h, want %h", ec_tick, 1'h1); errors = errors + 1; end
    if (status !== 4'h1) begin $display("FAIL vector 1: status = %h, want %h", status, 4'h1); errors = errors + 1; end
    // vector 2
    src0 = 1'h0;
    src1 = 1'h1;
    src2 = 1'h0;
    src3 = 1'h0;
    src_en = 4'h9;
    omega_we = 1'h0;
    omega_d = 32'h1183105D;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (64) tick;
    if (phase_out !== 32'h05C1D195) begin $display("FAIL vector 2: phase_out = %h, want %h", phase_out, 32'h05C1D195); errors = errors + 1; end
    if (freq_out !== 32'h105150D0) begin $display("FAIL vector 2: freq_out = %h, want %h", freq_out, 32'h105150D0); errors = errors + 1; end
    if (wrap !== 4'hF) begin $display("FAIL vector 2: wrap = %h, want %h", wrap, 4'hF); errors = errors + 1; end
    if (near !== 6'h3F) begin $display("FAIL vector 2: near = %h, want %h", near, 6'h3F); errors = errors + 1; end
    if (fault !== 4'h0) begin $display("FAIL vector 2: fault = %h, want %h", fault, 4'h0); errors = errors + 1; end
    if (lost !== 4'h0) begin $display("FAIL vector 2: lost = %h, want %h", lost, 4'h0); errors = errors + 1; end
    if (locked !== 4'h0) begin $display("FAIL vector 2: locked = %h, want %h", locked, 4'h0); errors = errors + 1; end
    if (glitch !== 4'h0) begin $display("FAIL vector 2: glitch = %h, want %h", glitch, 4'h0); errors = errors + 1; end
    if (coherent !== 1'h1) begin $display("FAIL vector 2: coherent = %h, want %h", coherent, 1'h1); errors = errors + 1; end
    if (quorum !== 1'h1) begin $display("FAIL vector 2: quorum = %h, want %h", quorum, 1'h1); errors = errors + 1; end
    if (ec_tick !== 1'h1) begin $display("FAIL vector 2: ec_tick = %h, want %h", ec_tick, 1'h1); errors = errors + 1; end
    if (status !== 4'h1) begin $display("FAIL vector 2: status = %h, want %h", status, 4'h1); errors = errors + 1; end
    // vector 3
    src0 = 1'h0;
    src1 = 1'h0;
    src2 = 1'h0;
    src3 = 1'h0;
    src_en = 4'h3;
    omega_we = 1'h0;
    omega_d = 32'h10B5EB4F;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (64) tick;
    if (phase_out !== 32'h05C1D195) begin $display("FAIL vector 3: phase_out = %h, want %h", phase_out, 32'h05C1D195); errors = errors + 1; end
    if (freq_out !== 32'h105150D0) begin $display("FAIL vector 3: freq_out = %h, want %h", freq_out, 32'h105150D0); errors = errors + 1; end
    if (wrap !== 4'hF) begin $display("FAIL vector 3: wrap = %h, want %h", wrap, 4'hF); errors = errors + 1; end
    if (near !== 6'h3F) begin $display("FAIL vector 3: near = %h, want %h", near, 6'h3F); errors = errors + 1; end
    if (fault !== 4'h0) begin $display("FAIL vector 3: fault = %h, want %h", fault, 4'h0); errors = errors + 1; end
    if (lost !== 4'h0) begin $display("FAIL vector 3: lost = %h, want %h", lost, 4'h0); errors = errors + 1; end
    if (locked !== 4'h0) begin $display("FAIL vector 3: locked = %h, want %h", locked, 4'h0); errors = errors + 1; end
    if (glitch !== 4'h0) begin $display("FAIL vector 3: glitch = %h, want %h", glitch, 4'h0); errors = errors + 1; end
    if (coherent !== 1'h1) begin $display("FAIL vector 3: coherent = %h, want %h", coherent, 1'h1); errors = errors + 1; end
    if (quorum !== 1'h1) begin $display("FAIL vector 3: quorum = %h, want %h", quorum, 1'h1); errors = errors + 1; end
    if (ec_tick !== 1'h1) begin $display("FAIL vector 3: ec_tick = %h, want %h", ec_tick, 1'h1); errors = errors + 1; end
    if (status !== 4'h1) begin $display("FAIL vector 3: status = %h, want %h", status, 4'h1); errors = errors + 1; end
    // vector 4
    src0 = 1'h0;
    src1 = 1'h1;
    src2 = 1'h1;
    src3 = 1'h1;
    src_en = 4'hD;
    omega_we = 1'h0;
    omega_d = 32'h0EDBD022;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (64) tick;
    if (phase_out !== 32'h08706CDC) begin $display("FAIL vector 4: phase_out = %h, want %h", phase_out, 32'h08706CDC); errors = errors + 1; end
    if (freq_out !== 32'h105220B5) begin $display("FAIL vector 4: freq_out = %h, want %h", freq_out, 32'h105220B5); errors = errors + 1; end
    if (wrap !== 4'hF) begin $display("FAIL vector 4: wrap = %h, want %h", wrap, 4'hF); errors = errors + 1; end
    if (near !== 6'h3F) begin $display("FAIL vector 4: near = %h, want %h", near, 6'h3F); errors = errors + 1; end
    if (fault !== 4'h0) begin $display("FAIL vector 4: fault = %h, want %h", fault, 4'h0); errors = errors + 1; end
    if (lost !== 4'h0) begin $display("FAIL vector 4: lost = %h, want %h", lost, 4'h0); errors = errors + 1; end
    if (locked !== 4'h0) begin $display("FAIL vector 4: locked = %h, want %h", locked, 4'h0); errors = errors + 1; end
    if (glitch !== 4'h0) begin $display("FAIL vector 4: glitch = %h, want %h", glitch, 4'h0); errors = errors + 1; end
    if (coherent !== 1'h1) begin $display("FAIL vector 4: coherent = %h, want %h", coherent, 1'h1); errors = errors + 1; end
    if (quorum !== 1'h1) begin $display("FAIL vector 4: quorum = %h, want %h", quorum, 1'h1); errors = errors + 1; end
    if (ec_tick !== 1'h1) begin $display("FAIL vector 4: ec_tick = %h, want %h", ec_tick, 1'h1); errors = errors + 1; end
    if (status !== 4'h1) begin $display("FAIL vector 4: status = %h, want %h", status, 4'h1); errors = errors + 1; end
    // vector 5
    src0 = 1'h1;
    src1 = 1'h0;
    src2 = 1'h0;
    src3 = 1'h1;
    src_en = 4'h3;
    omega_we = 1'h0;
    omega_d = 32'h1007B4DE;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (64) tick;
    if (phase_out !== 32'h0A1E5D65) begin $display("FAIL vector 5: phase_out = %h, want %h", phase_out, 32'h0A1E5D65); errors = errors + 1; end
    if (freq_out !== 32'h106BDC49) begin $display("FAIL vector 5: freq_out = %h, want %h", freq_out, 32'h106BDC49); errors = errors + 1; end
    if (wrap !== 4'hF) begin $display("FAIL vector 5: wrap = %h, want %h", wrap, 4'hF); errors = errors + 1; end
    if (near !== 6'h3F) begin $display("FAIL vector 5: near = %h, want %h", near, 6'h3F); errors = errors + 1; end
    if (fault !== 4'h0) begin $display("FAIL vector 5: fault = %h, want %h", fault, 4'h0); errors = errors + 1; end
    if (lost !== 4'h0) begin $display("FAIL vector 5: lost = %h, want %h", lost, 4'h0); errors = errors + 1; end
    if (locked !== 4'h0) begin $display("FAIL vector 5: locked = %h, want %h", locked, 4'h0); errors = errors + 1; end
    if (glitch !== 4'h0) begin $display("FAIL vector 5: glitch = %h, want %h", glitch, 4'h0); errors = errors + 1; end
    if (coherent !== 1'h1) begin $display("FAIL vector 5: coherent = %h, want %h", coherent, 1'h1); errors = errors + 1; end
    if (quorum !== 1'h1) begin $display("FAIL vector 5: quorum = %h, want %h", quorum, 1'h1); errors = errors + 1; end
    if (ec_tick !== 1'h1) begin $display("FAIL vector 5: ec_tick = %h, want %h", ec_tick, 1'h1); errors = errors + 1; end
    if (status !== 4'h1) begin $display("FAIL vector 5: status = %h, want %h", status, 4'h1); errors = errors + 1; end
    // vector 6
    src0 = 1'h1;
    src1 = 1'h0;
    src2 = 1'h0;
    src3 = 1'h1;
    src_en = 4'hB;
    omega_we = 1'h1;
    omega_d = 32'h0E235DD0;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (64) tick;
    if (phase_out !== 32'h779EF438) begin $display("FAIL vector 6: phase_out = %h, want %h", phase_out, 32'h779EF438); errors = errors + 1; end
    if (freq_out !== 32'h0E235DD0) begin $display("FAIL vector 6: freq_out = %h, want %h", freq_out, 32'h0E235DD0); errors = errors + 1; end
    if (wrap !== 4'h0) begin $display("FAIL vector 6: wrap = %h, want %h", wrap, 4'h0); errors = errors + 1; end
    if (near !== 6'h3F) begin $display("FAIL vector 6: near = %h, want %h", near, 6'h3F); errors = errors + 1; end
    if (fault !== 4'h0) begin $display("FAIL vector 6: fault = %h, want %h", fault, 4'h0); errors = errors + 1; end
    if (lost !== 4'h0) begin $display("FAIL vector 6: lost = %h, want %h", lost, 4'h0); errors = errors + 1; end
    if (locked !== 4'h0) begin $display("FAIL vector 6: locked = %h, want %h", locked, 4'h0); errors = errors + 1; end
    if (glitch !== 4'h0) begin $display("FAIL vector 6: glitch = %h, want %h", glitch, 4'h0); errors = errors + 1; end
    if (coherent !== 1'h1) begin $display("FAIL vector 6: coherent = %h, want %h", coherent, 1'h1); errors = errors + 1; end
    if (quorum !== 1'h1) begin $display("FAIL vector 6: quorum = %h, want %h", quorum, 1'h1); errors = errors + 1; end
    if (ec_tick !== 1'h0) begin $display("FAIL vector 6: ec_tick = %h, want %h", ec_tick, 1'h0); errors = errors + 1; end
    if (status !== 4'h1) begin $display("FAIL vector 6: status = %h, want %h", status, 4'h1); errors = errors + 1; end
    // vector 7
    src0 = 1'h0;
    src1 = 1'h1;
    src2 = 1'h1;
    src3 = 1'h1;
    src_en = 4'h5;
    omega_we = 1'h0;
    omega_d = 32'h0E8B5843;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (64) tick;
    if (phase_out !== 32'h0AA96923) begin $display("FAIL vector 7: phase_out = %h, want %h", phase_out, 32'h0AA96923); errors = errors + 1; end
    if (freq_out !== 32'h1056C28A) begin $display("FAIL vector 7: freq_out = %h, want %h", freq_out, 32'h1056C28A); errors = errors + 1; end
    if (wrap !== 4'hF) begin $display("FAIL vector 7: wrap = %h, want %h", wrap, 4'hF); errors = errors + 1; end
    if (near !== 6'h3F) begin $display("FAIL vector 7: near = %h, want %h", near, 6'h3F); errors = errors + 1; end
    if (fault !== 4'h0) begin $display("FAIL vector 7: fault = %h, want %h", fault, 4'h0); errors = errors + 1; end
    if (lost !== 4'h0) begin $display("FAIL vector 7: lost = %h, want %h", lost, 4'h0); errors = errors + 1; end
    if (locked !== 4'h0) begin $display("FAIL vector 7: locked = %h, want %h", locked, 4'h0); errors = errors + 1; end
    if (glitch !== 4'h0) begin $display("FAIL vector 7: glitch = %h, want %h", glitch, 4'h0); errors = errors + 1; end
    if (coherent !== 1'h1) begin $display("FAIL vector 7: coherent = %h, want %h", coherent, 1'h1); errors = errors + 1; end
    if (quorum !== 1'h1) begin $display("FAIL vector 7: quorum = %h, want %h", quorum, 1'h1); errors = errors + 1; end
    if (ec_tick !== 1'h1) begin $display("FAIL vector 7: ec_tick = %h, want %h", ec_tick, 1'h1); errors = errors + 1; end
    if (status !== 4'h1) begin $display("FAIL vector 7: status = %h, want %h", status, 4'h1); errors = errors + 1; end
    // vector 8
    src0 = 1'h0;
    src1 = 1'h0;
    src2 = 1'h0;
    src3 = 1'h1;
    src_en = 4'h3;
    omega_we = 1'h0;
    omega_d = 32'h105ED74E;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (64) tick;
    if (phase_out !== 32'h05C1D195) begin $display("FAIL vector 8: phase_out = %h, want %h", phase_out, 32'h05C1D195); errors = errors + 1; end
    if (freq_out !== 32'h105150D0) begin $display("FAIL vector 8: freq_out = %h, want %h", freq_out, 32'h105150D0); errors = errors + 1; end
    if (wrap !== 4'hF) begin $display("FAIL vector 8: wrap = %h, want %h", wrap, 4'hF); errors = errors + 1; end
    if (near !== 6'h3F) begin $display("FAIL vector 8: near = %h, want %h", near, 6'h3F); errors = errors + 1; end
    if (fault !== 4'h0) begin $display("FAIL vector 8: fault = %h, want %h", fault, 4'h0); errors = errors + 1; end
    if (lost !== 4'h0) begin $display("FAIL vector 8: lost = %h, want %h", lost, 4'h0); errors = errors + 1; end
    if (locked !== 4'h0) begin $display("FAIL vector 8: locked = %h, want %h", locked, 4'h0); errors = errors + 1; end
    if (glitch !== 4'h0) begin $display("FAIL vector 8: glitch = %h, want %h", glitch, 4'h0); errors = errors + 1; end
    if (coherent !== 1'h1) begin $display("FAIL vector 8: coherent = %h, want %h", coherent, 1'h1); errors = errors + 1; end
    if (quorum !== 1'h1) begin $display("FAIL vector 8: quorum = %h, want %h", quorum, 1'h1); errors = errors + 1; end
    if (ec_tick !== 1'h1) begin $display("FAIL vector 8: ec_tick = %h, want %h", ec_tick, 1'h1); errors = errors + 1; end
    if (status !== 4'h1) begin $display("FAIL vector 8: status = %h, want %h", status, 4'h1); errors = errors + 1; end
    // vector 9
    src0 = 1'h0;
    src1 = 1'h0;
    src2 = 1'h0;
    src3 = 1'h1;
    src_en = 4'h8;
    omega_we = 1'h0;
    omega_d = 32'h112F704E;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (64) tick;
    if (phase_out !== 32'h039B0265) begin $display("FAIL vector 9: phase_out = %h, want %h", phase_out, 32'h039B0265); errors = errors + 1; end
    if (freq_out !== 32'h104CEE6E) begin $display("FAIL vector 9: freq_out = %h, want %h", freq_out, 32'h104CEE6E); errors = errors + 1; end
    if (wrap !== 4'hF) begin $display("FAIL vector 9: wrap = %h, want %h", wrap, 4'hF); errors = errors + 1; end
    if (near !== 6'h3F) begin $display("FAIL vector 9: near = %h, want %h", near, 6'h3F); errors = errors + 1; end
    if (fault !== 4'h0) begin $display("FAIL vector 9: fault = %h, want %h", fault, 4'h0); errors = errors + 1; end
    if (lost !== 4'h0) begin $display("FAIL vector 9: lost = %h, want %h", lost, 4'h0); errors = errors + 1; end
    if (locked !== 4'h0) begin $display("FAIL vector 9: locked = %h, want %h", locked, 4'h0); errors = errors + 1; end
    if (glitch !== 4'h0) begin $display("FAIL vector 9: glitch = %h, want %h", glitch, 4'h0); errors = errors + 1; end
    if (coherent !== 1'h1) begin $display("FAIL vector 9: coherent = %h, want %h", coherent, 1'h1); errors = errors + 1; end
    if (quorum !== 1'h1) begin $display("FAIL vector 9: quorum = %h, want %h", quorum, 1'h1); errors = errors + 1; end
    if (ec_tick !== 1'h1) begin $display("FAIL vector 9: ec_tick = %h, want %h", ec_tick, 1'h1); errors = errors + 1; end
    if (status !== 4'h1) begin $display("FAIL vector 9: status = %h, want %h", status, 4'h1); errors = errors + 1; end
    // vector 10
    src0 = 1'h0;
    src1 = 1'h1;
    src2 = 1'h1;
    src3 = 1'h0;
    src_en = 4'hB;
    omega_we = 1'h0;
    omega_d = 32'h102006CF;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (64) tick;
    if (phase_out !== 32'hFDAD532C) begin $display("FAIL vector 10: phase_out = %h, want %h", phase_out, 32'hFDAD532C); errors = errors + 1; end
    if (freq_out !== 32'h1046B862) begin $display("FAIL vector 10: freq_out = %h, want %h", freq_out, 32'h1046B862); errors = errors + 1; end
    if (wrap !== 4'h0) begin $display("FAIL vector 10: wrap = %h, want %h", wrap, 4'h0); errors = errors + 1; end
    if (near !== 6'h3F) begin $display("FAIL vector 10: near = %h, want %h", near, 6'h3F); errors = errors + 1; end
    if (fault !== 4'h0) begin $display("FAIL vector 10: fault = %h, want %h", fault, 4'h0); errors = errors + 1; end
    if (lost !== 4'h0) begin $display("FAIL vector 10: lost = %h, want %h", lost, 4'h0); errors = errors + 1; end
    if (locked !== 4'h0) begin $display("FAIL vector 10: locked = %h, want %h", locked, 4'h0); errors = errors + 1; end
    if (glitch !== 4'h0) begin $display("FAIL vector 10: glitch = %h, want %h", glitch, 4'h0); errors = errors + 1; end
    if (coherent !== 1'h1) begin $display("FAIL vector 10: coherent = %h, want %h", coherent, 1'h1); errors = errors + 1; end
    if (quorum !== 1'h1) begin $display("FAIL vector 10: quorum = %h, want %h", quorum, 1'h1); errors = errors + 1; end
    if (ec_tick !== 1'h0) begin $display("FAIL vector 10: ec_tick = %h, want %h", ec_tick, 1'h0); errors = errors + 1; end
    if (status !== 4'h1) begin $display("FAIL vector 10: status = %h, want %h", status, 4'h1); errors = errors + 1; end
    // vector 11
    src0 = 1'h0;
    src1 = 1'h0;
    src2 = 1'h1;
    src3 = 1'h0;
    src_en = 4'hE;
    omega_we = 1'h0;
    omega_d = 32'h101724B2;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (64) tick;
    if (phase_out !== 32'h0AA96923) begin $display("FAIL vector 11: phase_out = %h, want %h", phase_out, 32'h0AA96923); errors = errors + 1; end
    if (freq_out !== 32'h1056C28A) begin $display("FAIL vector 11: freq_out = %h, want %h", freq_out, 32'h1056C28A); errors = errors + 1; end
    if (wrap !== 4'hF) begin $display("FAIL vector 11: wrap = %h, want %h", wrap, 4'hF); errors = errors + 1; end
    if (near !== 6'h3F) begin $display("FAIL vector 11: near = %h, want %h", near, 6'h3F); errors = errors + 1; end
    if (fault !== 4'h0) begin $display("FAIL vector 11: fault = %h, want %h", fault, 4'h0); errors = errors + 1; end
    if (lost !== 4'h0) begin $display("FAIL vector 11: lost = %h, want %h", lost, 4'h0); errors = errors + 1; end
    if (locked !== 4'h0) begin $display("FAIL vector 11: locked = %h, want %h", locked, 4'h0); errors = errors + 1; end
    if (glitch !== 4'h0) begin $display("FAIL vector 11: glitch = %h, want %h", glitch, 4'h0); errors = errors + 1; end
    if (coherent !== 1'h1) begin $display("FAIL vector 11: coherent = %h, want %h", coherent, 1'h1); errors = errors + 1; end
    if (quorum !== 1'h1) begin $display("FAIL vector 11: quorum = %h, want %h", quorum, 1'h1); errors = errors + 1; end
    if (ec_tick !== 1'h1) begin $display("FAIL vector 11: ec_tick = %h, want %h", ec_tick, 1'h1); errors = errors + 1; end
    if (status !== 4'h1) begin $display("FAIL vector 11: status = %h, want %h", status, 4'h1); errors = errors + 1; end
    // vector 12
    src0 = 1'h1;
    src1 = 1'h0;
    src2 = 1'h0;
    src3 = 1'h0;
    src_en = 4'h5;
    omega_we = 1'h1;
    omega_d = 32'h0FF3117D;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (64) tick;
    if (phase_out !== 32'hEB79DE68) begin $display("FAIL vector 12: phase_out = %h, want %h", phase_out, 32'hEB79DE68); errors = errors + 1; end
    if (freq_out !== 32'h0FF3117D) begin $display("FAIL vector 12: freq_out = %h, want %h", freq_out, 32'h0FF3117D); errors = errors + 1; end
    if (wrap !== 4'h0) begin $display("FAIL vector 12: wrap = %h, want %h", wrap, 4'h0); errors = errors + 1; end
    if (near !== 6'h3F) begin $display("FAIL vector 12: near = %h, want %h", near, 6'h3F); errors = errors + 1; end
    if (fault !== 4'h0) begin $display("FAIL vector 12: fault = %h, want %h", fault, 4'h0); errors = errors + 1; end
    if (lost !== 4'h0) begin $display("FAIL vector 12: lost = %h, want %h", lost, 4'h0); errors = errors + 1; end
    if (locked !== 4'h0) begin $display("FAIL vector 12: locked = %h, want %h", locked, 4'h0); errors = errors + 1; end
    if (glitch !== 4'h0) begin $display("FAIL vector 12: glitch = %h, want %h", glitch, 4'h0); errors = errors + 1; end
    if (coherent !== 1'h1) begin $display("FAIL vector 12: coherent = %h, want %h", coherent, 1'h1); errors = errors + 1; end
    if (quorum !== 1'h1) begin $display("FAIL vector 12: quorum = %h, want %h", quorum, 1'h1); errors = errors + 1; end
    if (ec_tick !== 1'h0) begin $display("FAIL vector 12: ec_tick = %h, want %h", ec_tick, 1'h0); errors = errors + 1; end
    if (status !== 4'h1) begin $display("FAIL vector 12: status = %h, want %h", status, 4'h1); errors = errors + 1; end
    // vector 13
    src0 = 1'h0;
    src1 = 1'h0;
    src2 = 1'h0;
    src3 = 1'h1;
    src_en = 4'h6;
    omega_we = 1'h0;
    omega_d = 32'h108FFF57;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (64) tick;
    if (phase_out !== 32'h05C1D195) begin $display("FAIL vector 13: phase_out = %h, want %h", phase_out, 32'h05C1D195); errors = errors + 1; end
    if (freq_out !== 32'h105150D0) begin $display("FAIL vector 13: freq_out = %h, want %h", freq_out, 32'h105150D0); errors = errors + 1; end
    if (wrap !== 4'hF) begin $display("FAIL vector 13: wrap = %h, want %h", wrap, 4'hF); errors = errors + 1; end
    if (near !== 6'h3F) begin $display("FAIL vector 13: near = %h, want %h", near, 6'h3F); errors = errors + 1; end
    if (fault !== 4'h0) begin $display("FAIL vector 13: fault = %h, want %h", fault, 4'h0); errors = errors + 1; end
    if (lost !== 4'h0) begin $display("FAIL vector 13: lost = %h, want %h", lost, 4'h0); errors = errors + 1; end
    if (locked !== 4'h0) begin $display("FAIL vector 13: locked = %h, want %h", locked, 4'h0); errors = errors + 1; end
    if (glitch !== 4'h0) begin $display("FAIL vector 13: glitch = %h, want %h", glitch, 4'h0); errors = errors + 1; end
    if (coherent !== 1'h1) begin $display("FAIL vector 13: coherent = %h, want %h", coherent, 1'h1); errors = errors + 1; end
    if (quorum !== 1'h1) begin $display("FAIL vector 13: quorum = %h, want %h", quorum, 1'h1); errors = errors + 1; end
    if (ec_tick !== 1'h1) begin $display("FAIL vector 13: ec_tick = %h, want %h", ec_tick, 1'h1); errors = errors + 1; end
    if (status !== 4'h1) begin $display("FAIL vector 13: status = %h, want %h", status, 4'h1); errors = errors + 1; end
    // vector 14
    src0 = 1'h1;
    src1 = 1'h1;
    src2 = 1'h0;
    src3 = 1'h0;
    src_en = 4'h0;
    omega_we = 1'h0;
    omega_d = 32'h0EBD80A0;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (64) tick;
    if (phase_out !== 32'h05C1D195) begin $display("FAIL vector 14: phase_out = %h, want %h", phase_out, 32'h05C1D195); errors = errors + 1; end
    if (freq_out !== 32'h105150D0) begin $display("FAIL vector 14: freq_out = %h, want %h", freq_out, 32'h105150D0); errors = errors + 1; end
    if (wrap !== 4'hF) begin $display("FAIL vector 14: wrap = %h, want %h", wrap, 4'hF); errors = errors + 1; end
    if (near !== 6'h3F) begin $display("FAIL vector 14: near = %h, want %h", near, 6'h3F); errors = errors + 1; end
    if (fault !== 4'h0) begin $display("FAIL vector 14: fault = %h, want %h", fault, 4'h0); errors = errors + 1; end
    if (lost !== 4'h0) begin $display("FAIL vector 14: lost = %h, want %h", lost, 4'h0); errors = errors + 1; end
    if (locked !== 4'h0) begin $display("FAIL vector 14: locked = %h, want %h", locked, 4'h0); errors = errors + 1; end
    if (glitch !== 4'h0) begin $display("FAIL vector 14: glitch = %h, want %h", glitch, 4'h0); errors = errors + 1; end
    if (coherent !== 1'h1) begin $display("FAIL vector 14: coherent = %h, want %h", coherent, 1'h1); errors = errors + 1; end
    if (quorum !== 1'h1) begin $display("FAIL vector 14: quorum = %h, want %h", quorum, 1'h1); errors = errors + 1; end
    if (ec_tick !== 1'h1) begin $display("FAIL vector 14: ec_tick = %h, want %h", ec_tick, 1'h1); errors = errors + 1; end
    if (status !== 4'h1) begin $display("FAIL vector 14: status = %h, want %h", status, 4'h1); errors = errors + 1; end
    // vector 15
    src0 = 1'h1;
    src1 = 1'h0;
    src2 = 1'h1;
    src3 = 1'h1;
    src_en = 4'h3;
    omega_we = 1'h0;
    omega_d = 32'h0F1F1D27;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (64) tick;
    if (phase_out !== 32'h0A1E5D65) begin $display("FAIL vector 15: phase_out = %h, want %h", phase_out, 32'h0A1E5D65); errors = errors + 1; end
    if (freq_out !== 32'h106BDC49) begin $display("FAIL vector 15: freq_out = %h, want %h", freq_out, 32'h106BDC49); errors = errors + 1; end
    if (wrap !== 4'hF) begin $display("FAIL vector 15: wrap = %h, want %h", wrap, 4'hF); errors = errors + 1; end
    if (near !== 6'h3F) begin $display("FAIL vector 15: near = %h, want %h", near, 6'h3F); errors = errors + 1; end
    if (fault !== 4'h0) begin $display("FAIL vector 15: fault = %h, want %h", fault, 4'h0); errors = errors + 1; end
    if (lost !== 4'h0) begin $display("FAIL vector 15: lost = %h, want %h", lost, 4'h0); errors = errors + 1; end
    if (locked !== 4'h0) begin $display("FAIL vector 15: locked = %h, want %h", locked, 4'h0); errors = errors + 1; end
    if (glitch !== 4'h0) begin $display("FAIL vector 15: glitch = %h, want %h", glitch, 4'h0); errors = errors + 1; end
    if (coherent !== 1'h1) begin $display("FAIL vector 15: coherent = %h, want %h", coherent, 1'h1); errors = errors + 1; end
    if (quorum !== 1'h1) begin $display("FAIL vector 15: quorum = %h, want %h", quorum, 1'h1); errors = errors + 1; end
    if (ec_tick !== 1'h1) begin $display("FAIL vector 15: ec_tick = %h, want %h", ec_tick, 1'h1); errors = errors + 1; end
    if (status !== 4'h1) begin $display("FAIL vector 15: status = %h, want %h", status, 4'h1); errors = errors + 1; end
    if (errors == 0) $display("PASS jev_kuramoto: 16 vectors");
    else $display("FAIL jev_kuramoto: %0d mismatches", errors);
    $finish;
  end
endmodule
