// jev_kuramoto.v -- generated by the WASMApollo EDA (heapvm vgpu apollo) from typed fabric `jev_kuramoto`.
// 151 LUT4 cells, 584 word PEs, 62 registers, 10 combinational levels.
// Clocking matches the vFPGA / vASIC fabric: each rising clk edge latches every register
// from the settled levels; rst (synchronous) loads the fabric's initial state.
// Jev microcode ROM `jev_listen0`: controller state -> Jev's answer -> select code (LSB first: rom_166 rom_167 rom_168)
//   state  answer        p      code
//   0      abc           1.000  111
//   1      bc            1.000  110
//   2      ac            1.000  101
//   3      c             1.000  100
//   4      ab            1.000  011
//   5      b             1.000  010
//   6      a             1.000  001
//   7      none          1.000  000
//   8      none          1.000  000
//   9      none          1.000  000
//   10     none          1.000  000
//   11     none          1.000  000
//   12     none          1.000  000
//   13     none          1.000  000
//   14     none          1.000  000
//   15     none          1.000  000
// Jev microcode ROM `jev_listen1`: controller state -> Jev's answer -> select code (LSB first: rom_320 rom_321 rom_322)
//   state  answer        p      code
//   0      abc           1.000  111
//   1      bc            1.000  110
//   2      ac            1.000  101
//   3      c             1.000  100
//   4      ab            1.000  011
//   5      b             1.000  010
//   6      a             1.000  001
//   7      none          1.000  000
//   8      none          1.000  000
//   9      none          1.000  000
//   10     none          1.000  000
//   11     none          1.000  000
//   12     none          1.000  000
//   13     none          1.000  000
//   14     none          1.000  000
//   15     none          1.000  000
// Jev microcode ROM `jev_listen2`: controller state -> Jev's answer -> select code (LSB first: rom_474 rom_475 rom_476)
//   state  answer        p      code
//   0      abc           1.000  111
//   1      bc            1.000  110
//   2      ac            1.000  101
//   3      c             1.000  100
//   4      ab            1.000  011
//   5      b             1.000  010
//   6      a             1.000  001
//   7      none          1.000  000
//   8      none          1.000  000
//   9      none          1.000  000
//   10     none          1.000  000
//   11     none          1.000  000
//   12     none          1.000  000
//   13     none          1.000  000
//   14     none          1.000  000
//   15     none          1.000  000
// Jev microcode ROM `jev_listen3`: controller state -> Jev's answer -> select code (LSB first: rom_628 rom_629 rom_630)
//   state  answer        p      code
//   0      abc           1.000  111
//   1      bc            1.000  110
//   2      ac            1.000  101
//   3      c             1.000  100
//   4      ab            1.000  011
//   5      b             1.000  010
//   6      a             1.000  001
//   7      none          1.000  000
//   8      none          1.000  000
//   9      none          1.000  000
//   10     none          1.000  000
//   11     none          1.000  000
//   12     none          1.000  000
//   13     none          1.000  000
//   14     none          1.000  000
//   15     none          1.000  000
// Jev microcode ROM `jev_strobe`: controller state -> Jev's answer -> select code (LSB first: rom_782 rom_783 rom_784)
//   state  answer        p      code
//   0      n0            1.000  000
//   1      n1            1.000  001
//   2      n0            1.000  000
//   3      n2            1.000  010
//   4      n0            1.000  000
//   5      n1            1.000  001
//   6      n0            1.000  000
//   7      n3            1.000  011
//   8      n0            1.000  000
//   9      n1            1.000  001
//   10     n0            1.000  000
//   11     n2            1.000  010
//   12     n0            1.000  000
//   13     n1            1.000  001
//   14     n0            1.000  000
//   15     hold          1.000  100

`timescale 1ns/1ps
module jev_kuramoto (
  input  wire        clk,
  input  wire        rst,
  input  wire src0,
  input  wire src1,
  input  wire src2,
  input  wire src3,
  input  wire [3:0] src_en,
  input  wire omega_we,
  input  wire [31:0] omega_d,
  output wire [31:0] phase_out,
  output wire [31:0] freq_out,
  output wire [3:0] wrap,
  output wire [5:0] near,
  output wire [3:0] fault,
  output wire [3:0] lost,
  output wire [3:0] locked,
  output wire [3:0] glitch,
  output wire coherent,
  output wire quorum,
  output wire ec_tick,
  output wire [3:0] status
);

  function lut4(input [15:0] t, input [3:0] i);  // a LUT4 cell: row i of truth table t
    lut4 = t[i];
  endfunction

  // registers
  reg xs1_0 = 1'h0;
  reg xs2_0 = 1'h0;
  reg xs3_0 = 1'h0;
  reg [31:0] hi_0 = 32'h00000000;
  reg lk_0 = 1'h0;
  reg [31:0] th_0 = 32'h00000000;
  reg [31:0] om_0 = 32'h10000000;
  reg [31:0] qt_0 = 32'h00000000;
  reg [31:0] cp_0 = 32'h00000000;
  reg [31:0] ad_0 = 32'h00000000;
  reg [31:0] ij_0 = 32'h00000000;
  reg [31:0] fj_0 = 32'h00000000;
  reg sl_0 = 1'h0;
  reg xs1_1 = 1'h0;
  reg xs2_1 = 1'h0;
  reg xs3_1 = 1'h0;
  reg [31:0] hi_1 = 32'h00000000;
  reg lk_1 = 1'h0;
  reg [31:0] th_1 = 32'h50000000;
  reg [31:0] om_1 = 32'h10F5C28F;
  reg [31:0] qt_1 = 32'h00000000;
  reg [31:0] cp_1 = 32'h00000000;
  reg [31:0] ad_1 = 32'h00000000;
  reg [31:0] ij_1 = 32'h00000000;
  reg [31:0] fj_1 = 32'h00000000;
  reg sl_1 = 1'h0;
  reg xs1_2 = 1'h0;
  reg xs2_2 = 1'h0;
  reg xs3_2 = 1'h0;
  reg [31:0] hi_2 = 32'h00000000;
  reg lk_2 = 1'h0;
  reg [31:0] th_2 = 32'hA0000000;
  reg [31:0] om_2 = 32'h0F333333;
  reg [31:0] qt_2 = 32'h00000000;
  reg [31:0] cp_2 = 32'h00000000;
  reg [31:0] ad_2 = 32'h00000000;
  reg [31:0] ij_2 = 32'h00000000;
  reg [31:0] fj_2 = 32'h00000000;
  reg sl_2 = 1'h0;
  reg xs1_3 = 1'h0;
  reg xs2_3 = 1'h0;
  reg xs3_3 = 1'h0;
  reg [31:0] hi_3 = 32'h00000000;
  reg lk_3 = 1'h0;
  reg [31:0] th_3 = 32'hF0000000;
  reg [31:0] om_3 = 32'h107AE148;
  reg [31:0] qt_3 = 32'h00000000;
  reg [31:0] cp_3 = 32'h00000000;
  reg [31:0] ad_3 = 32'h00000000;
  reg [31:0] ij_3 = 32'h00000000;
  reg [31:0] fj_3 = 32'h00000000;
  reg sl_3 = 1'h0;
  reg nq01 = 1'h0;
  reg nq02 = 1'h0;
  reg nq03 = 1'h0;
  reg nq12 = 1'h0;
  reg nq13 = 1'h0;
  reg nq23 = 1'h0;
  reg sta_0 = 1'h0;
  reg sta_1 = 1'h0;
  reg sta_2 = 1'h0;
  reg sta_3 = 1'h0;

  // level 0
  wire [31:0] k_64 = 32'h00000000;
  wire [31:0] k_65 = 32'h00000001;
  wire [31:0] k_66 = 32'hFFFFFFFF;
  wire [31:0] k_67 = 32'h10000000;
  wire [31:0] k_68 = 32'h40000000;
  wire [31:0] k_69 = 32'h000000FF;
  wire [31:0] pe2_70 = (th_1 - th_0);
  wire [31:0] pe2_71 = (th_0 - th_1);
  wire [31:0] k_73 = 32'h0000001F;
  wire [31:0] k_75 = 32'h00000001;
  wire [31:0] pe2_80 = (th_2 - th_0);
  wire [31:0] pe2_81 = (th_0 - th_2);
  wire [31:0] k_83 = 32'h0000001F;
  wire [31:0] k_85 = 32'h00000001;
  wire [31:0] pe2_90 = (th_3 - th_0);
  wire [31:0] pe2_91 = (th_0 - th_3);
  wire [31:0] k_93 = 32'h0000001F;
  wire [31:0] k_95 = 32'h00000001;
  wire [31:0] pe2_100 = (th_2 - th_1);
  wire [31:0] pe2_101 = (th_1 - th_2);
  wire [31:0] k_103 = 32'h0000001F;
  wire [31:0] k_105 = 32'h00000001;
  wire [31:0] pe2_110 = (th_3 - th_1);
  wire [31:0] pe2_111 = (th_1 - th_3);
  wire [31:0] k_113 = 32'h0000001F;
  wire [31:0] k_115 = 32'h00000001;
  wire [31:0] pe2_120 = (th_3 - th_2);
  wire [31:0] pe2_121 = (th_2 - th_3);
  wire [31:0] k_123 = 32'h0000001F;
  wire [31:0] k_125 = 32'h00000001;
  wire and4_130 = lut4(16'h8000, {1'b1, nq23, nq13, nq12});
  wire and4_131 = lut4(16'h8000, {1'b1, nq23, nq03, nq02});
  wire and4_132 = lut4(16'h8000, {1'b1, nq13, nq03, nq01});
  wire and4_133 = lut4(16'h8000, {1'b1, nq12, nq02, nq01});
  wire and4_135 = lut4(16'h8000, {nq12, nq03, nq02, nq01});
  wire and4_136 = lut4(16'h8000, {1'b1, 1'b1, nq23, nq13});
  wire or4_138 = lut4(16'hFFFE, {1'b0, nq03, nq02, nq01});
  wire or4_145 = lut4(16'hFFFE, {1'b0, nq13, nq12, nq01});
  wire or4_152 = lut4(16'hFFFE, {1'b0, nq23, nq12, nq02});
  wire or4_159 = lut4(16'hFFFE, {1'b0, nq23, nq13, nq03});
  wire [31:0] k_169 = 32'h00000004;
  wire [31:0] k_170 = 32'h0000001F;
  wire [31:0] k_172 = 32'h00000001;
  wire [31:0] k_181 = 32'h00000008;
  wire [31:0] k_182 = 32'h0000001F;
  wire [31:0] k_184 = 32'h00000001;
  wire [31:0] k_193 = 32'h0000001F;
  wire [31:0] k_195 = 32'h00000001;
  wire not_197 = lut4(16'h5555, {1'b0, 1'b0, 1'b0, nq01});
  wire [31:0] k_199 = 32'h00000004;
  wire [31:0] k_200 = 32'h0000001F;
  wire [31:0] k_202 = 32'h00000001;
  wire [31:0] k_211 = 32'h00000008;
  wire [31:0] k_212 = 32'h0000001F;
  wire [31:0] k_214 = 32'h00000001;
  wire [31:0] k_223 = 32'h0000001F;
  wire [31:0] k_225 = 32'h00000001;
  wire not_227 = lut4(16'h5555, {1'b0, 1'b0, 1'b0, nq02});
  wire [31:0] k_229 = 32'h00000004;
  wire [31:0] k_230 = 32'h0000001F;
  wire [31:0] k_232 = 32'h00000001;
  wire [31:0] k_241 = 32'h00000008;
  wire [31:0] k_242 = 32'h0000001F;
  wire [31:0] k_244 = 32'h00000001;
  wire [31:0] k_253 = 32'h0000001F;
  wire [31:0] k_255 = 32'h00000001;
  wire not_257 = lut4(16'h5555, {1'b0, 1'b0, 1'b0, nq03});
  wire not_259 = lut4(16'h5555, {1'b0, 1'b0, 1'b0, xs3_0});
  wire [31:0] k_262 = 32'h0000001F;
  wire [31:0] k_264 = 32'h00000001;
  wire not_269 = lut4(16'h5555, {1'b0, 1'b0, 1'b0, lk_0});
  wire [31:0] k_276 = 32'h00000002;
  wire [31:0] k_277 = 32'h0000001F;
  wire [31:0] k_279 = 32'h00000001;
  wire [31:0] k_287 = 32'h00000008;
  wire [31:0] k_288 = 32'h0000001F;
  wire [31:0] k_290 = 32'h00000001;
  wire [31:0] pe1_301 = (cp_0 + ij_0);
  wire [31:0] pe1_303 = (ad_0 + fj_0);
  wire [31:0] k_314 = 32'h0000001F;
  wire [31:0] k_316 = 32'h00000001;
  wire [31:0] k_323 = 32'h00000004;
  wire [31:0] k_324 = 32'h0000001F;
  wire [31:0] k_326 = 32'h00000001;
  wire [31:0] k_335 = 32'h00000008;
  wire [31:0] k_336 = 32'h0000001F;
  wire [31:0] k_338 = 32'h00000001;
  wire [31:0] k_347 = 32'h0000001F;
  wire [31:0] k_349 = 32'h00000001;
  wire not_351 = lut4(16'h5555, {1'b0, 1'b0, 1'b0, nq01});
  wire [31:0] k_353 = 32'h00000004;
  wire [31:0] k_354 = 32'h0000001F;
  wire [31:0] k_356 = 32'h00000001;
  wire [31:0] k_365 = 32'h00000008;
  wire [31:0] k_366 = 32'h0000001F;
  wire [31:0] k_368 = 32'h00000001;
  wire [31:0] k_377 = 32'h0000001F;
  wire [31:0] k_379 = 32'h00000001;
  wire not_381 = lut4(16'h5555, {1'b0, 1'b0, 1'b0, nq12});
  wire [31:0] k_383 = 32'h00000004;
  wire [31:0] k_384 = 32'h0000001F;
  wire [31:0] k_386 = 32'h00000001;
  wire [31:0] k_395 = 32'h00000008;
  wire [31:0] k_396 = 32'h0000001F;
  wire [31:0] k_398 = 32'h00000001;
  wire [31:0] k_407 = 32'h0000001F;
  wire [31:0] k_409 = 32'h00000001;
  wire not_411 = lut4(16'h5555, {1'b0, 1'b0, 1'b0, nq13});
  wire not_413 = lut4(16'h5555, {1'b0, 1'b0, 1'b0, xs3_1});
  wire [31:0] k_416 = 32'h0000001F;
  wire [31:0] k_418 = 32'h00000001;
  wire not_423 = lut4(16'h5555, {1'b0, 1'b0, 1'b0, lk_1});
  wire [31:0] k_430 = 32'h00000002;
  wire [31:0] k_431 = 32'h0000001F;
  wire [31:0] k_433 = 32'h00000001;
  wire [31:0] k_441 = 32'h00000008;
  wire [31:0] k_442 = 32'h0000001F;
  wire [31:0] k_444 = 32'h00000001;
  wire [31:0] pe1_455 = (cp_1 + ij_1);
  wire [31:0] pe1_457 = (ad_1 + fj_1);
  wire [31:0] k_468 = 32'h0000001F;
  wire [31:0] k_470 = 32'h00000001;
  wire [31:0] k_477 = 32'h00000004;
  wire [31:0] k_478 = 32'h0000001F;
  wire [31:0] k_480 = 32'h00000001;
  wire [31:0] k_489 = 32'h00000008;
  wire [31:0] k_490 = 32'h0000001F;
  wire [31:0] k_492 = 32'h00000001;
  wire [31:0] k_501 = 32'h0000001F;
  wire [31:0] k_503 = 32'h00000001;
  wire not_505 = lut4(16'h5555, {1'b0, 1'b0, 1'b0, nq02});
  wire [31:0] k_507 = 32'h00000004;
  wire [31:0] k_508 = 32'h0000001F;
  wire [31:0] k_510 = 32'h00000001;
  wire [31:0] k_519 = 32'h00000008;
  wire [31:0] k_520 = 32'h0000001F;
  wire [31:0] k_522 = 32'h00000001;
  wire [31:0] k_531 = 32'h0000001F;
  wire [31:0] k_533 = 32'h00000001;
  wire not_535 = lut4(16'h5555, {1'b0, 1'b0, 1'b0, nq12});
  wire [31:0] k_537 = 32'h00000004;
  wire [31:0] k_538 = 32'h0000001F;
  wire [31:0] k_540 = 32'h00000001;
  wire [31:0] k_549 = 32'h00000008;
  wire [31:0] k_550 = 32'h0000001F;
  wire [31:0] k_552 = 32'h00000001;
  wire [31:0] k_561 = 32'h0000001F;
  wire [31:0] k_563 = 32'h00000001;
  wire not_565 = lut4(16'h5555, {1'b0, 1'b0, 1'b0, nq23});
  wire not_567 = lut4(16'h5555, {1'b0, 1'b0, 1'b0, xs3_2});
  wire [31:0] k_570 = 32'h0000001F;
  wire [31:0] k_572 = 32'h00000001;
  wire not_577 = lut4(16'h5555, {1'b0, 1'b0, 1'b0, lk_2});
  wire [31:0] k_584 = 32'h00000002;
  wire [31:0] k_585 = 32'h0000001F;
  wire [31:0] k_587 = 32'h00000001;
  wire [31:0] k_595 = 32'h00000008;
  wire [31:0] k_596 = 32'h0000001F;
  wire [31:0] k_598 = 32'h00000001;
  wire [31:0] pe1_609 = (cp_2 + ij_2);
  wire [31:0] pe1_611 = (ad_2 + fj_2);
  wire [31:0] k_622 = 32'h0000001F;
  wire [31:0] k_624 = 32'h00000001;
  wire [31:0] k_631 = 32'h00000004;
  wire [31:0] k_632 = 32'h0000001F;
  wire [31:0] k_634 = 32'h00000001;
  wire [31:0] k_643 = 32'h00000008;
  wire [31:0] k_644 = 32'h0000001F;
  wire [31:0] k_646 = 32'h00000001;
  wire [31:0] k_655 = 32'h0000001F;
  wire [31:0] k_657 = 32'h00000001;
  wire not_659 = lut4(16'h5555, {1'b0, 1'b0, 1'b0, nq03});
  wire [31:0] k_661 = 32'h00000004;
  wire [31:0] k_662 = 32'h0000001F;
  wire [31:0] k_664 = 32'h00000001;
  wire [31:0] k_673 = 32'h00000008;
  wire [31:0] k_674 = 32'h0000001F;
  wire [31:0] k_676 = 32'h00000001;
  wire [31:0] k_685 = 32'h0000001F;
  wire [31:0] k_687 = 32'h00000001;
  wire not_689 = lut4(16'h5555, {1'b0, 1'b0, 1'b0, nq13});
  wire [31:0] k_691 = 32'h00000004;
  wire [31:0] k_692 = 32'h0000001F;
  wire [31:0] k_694 = 32'h00000001;
  wire [31:0] k_703 = 32'h00000008;
  wire [31:0] k_704 = 32'h0000001F;
  wire [31:0] k_706 = 32'h00000001;
  wire [31:0] k_715 = 32'h0000001F;
  wire [31:0] k_717 = 32'h00000001;
  wire not_719 = lut4(16'h5555, {1'b0, 1'b0, 1'b0, nq23});
  wire not_721 = lut4(16'h5555, {1'b0, 1'b0, 1'b0, xs3_3});
  wire [31:0] k_724 = 32'h0000001F;
  wire [31:0] k_726 = 32'h00000001;
  wire not_731 = lut4(16'h5555, {1'b0, 1'b0, 1'b0, lk_3});
  wire [31:0] k_738 = 32'h00000002;
  wire [31:0] k_739 = 32'h0000001F;
  wire [31:0] k_741 = 32'h00000001;
  wire [31:0] k_749 = 32'h00000008;
  wire [31:0] k_750 = 32'h0000001F;
  wire [31:0] k_752 = 32'h00000001;
  wire [31:0] pe1_763 = (cp_3 + ij_3);
  wire [31:0] pe1_765 = (ad_3 + fj_3);
  wire [31:0] k_776 = 32'h0000001F;
  wire [31:0] k_778 = 32'h00000001;
  wire n801 = lut4(16'hAAAA, {1'b0, 1'b0, 1'b0, xs1_0});
  wire n802 = lut4(16'hAAAA, {1'b0, 1'b0, 1'b0, xs2_0});
  wire n803 = lut4(16'hAAAA, {1'b0, 1'b0, 1'b0, xs1_1});
  wire n804 = lut4(16'hAAAA, {1'b0, 1'b0, 1'b0, xs2_1});
  wire n805 = lut4(16'hAAAA, {1'b0, 1'b0, 1'b0, xs1_2});
  wire n806 = lut4(16'hAAAA, {1'b0, 1'b0, 1'b0, xs2_2});
  wire n807 = lut4(16'hAAAA, {1'b0, 1'b0, 1'b0, xs1_3});
  wire n808 = lut4(16'hAAAA, {1'b0, 1'b0, 1'b0, xs2_3});

  // level 1
  wire [31:0] pe8_74 = (pe2_70 >> (k_73 & 32'd31));
  wire [31:0] pe2_77 = (k_64 - pe2_70);
  wire [31:0] pe8_84 = (pe2_80 >> (k_83 & 32'd31));
  wire [31:0] pe2_87 = (k_64 - pe2_80);
  wire [31:0] pe8_94 = (pe2_90 >> (k_93 & 32'd31));
  wire [31:0] pe2_97 = (k_64 - pe2_90);
  wire [31:0] pe8_104 = (pe2_100 >> (k_103 & 32'd31));
  wire [31:0] pe2_107 = (k_64 - pe2_100);
  wire [31:0] pe8_114 = (pe2_110 >> (k_113 & 32'd31));
  wire [31:0] pe2_117 = (k_64 - pe2_110);
  wire [31:0] pe8_124 = (pe2_120 >> (k_123 & 32'd31));
  wire [31:0] pe2_127 = (k_64 - pe2_120);
  wire or4_134 = lut4(16'hFFFE, {and4_133, and4_132, and4_131, and4_130});
  wire and4_137 = lut4(16'h8000, {1'b1, 1'b1, and4_136, and4_135});
  wire not_139 = lut4(16'h5555, {1'b0, 1'b0, 1'b0, or4_138});
  wire eq_141 = (qt_0 == k_69);
  wire not_146 = lut4(16'h5555, {1'b0, 1'b0, 1'b0, or4_145});
  wire eq_148 = (qt_1 == k_69);
  wire not_153 = lut4(16'h5555, {1'b0, 1'b0, 1'b0, or4_152});
  wire eq_155 = (qt_2 == k_69);
  wire not_160 = lut4(16'h5555, {1'b0, 1'b0, 1'b0, or4_159});
  wire eq_162 = (qt_3 == k_69);
  wire [31:0] pe8_171 = (pe2_70 >> (k_170 & 32'd31));
  wire [31:0] pe8_174 = (pe2_70 >> (k_169 & 32'd31));
  wire [31:0] pe6_175 = (pe2_70 ^ k_66);
  wire [31:0] pe8_183 = (pe2_70 >> (k_182 & 32'd31));
  wire [31:0] pe8_186 = (pe2_70 >> (k_181 & 32'd31));
  wire [31:0] pe6_187 = (pe2_70 ^ k_66);
  wire [31:0] pe8_194 = (pe2_70 >> (k_193 & 32'd31));
  wire [31:0] pe8_201 = (pe2_80 >> (k_200 & 32'd31));
  wire [31:0] pe8_204 = (pe2_80 >> (k_199 & 32'd31));
  wire [31:0] pe6_205 = (pe2_80 ^ k_66);
  wire [31:0] pe8_213 = (pe2_80 >> (k_212 & 32'd31));
  wire [31:0] pe8_216 = (pe2_80 >> (k_211 & 32'd31));
  wire [31:0] pe6_217 = (pe2_80 ^ k_66);
  wire [31:0] pe8_224 = (pe2_80 >> (k_223 & 32'd31));
  wire [31:0] pe8_231 = (pe2_90 >> (k_230 & 32'd31));
  wire [31:0] pe8_234 = (pe2_90 >> (k_229 & 32'd31));
  wire [31:0] pe6_235 = (pe2_90 ^ k_66);
  wire [31:0] pe8_243 = (pe2_90 >> (k_242 & 32'd31));
  wire [31:0] pe8_246 = (pe2_90 >> (k_241 & 32'd31));
  wire [31:0] pe6_247 = (pe2_90 ^ k_66);
  wire [31:0] pe8_254 = (pe2_90 >> (k_253 & 32'd31));
  wire and4_260 = lut4(16'h8000, {1'b1, src_en[0], not_259, xs2_0});
  wire [31:0] pe2_261 = (k_64 - th_0);
  wire [31:0] pe8_298 = (om_0 >> (k_65 & 32'd31));
  wire [31:0] pe1_304 = (om_0 + pe1_303);
  wire [31:0] pe1_306 = (qt_0 + k_65);
  wire [31:0] pe8_315 = (th_0 >> (k_314 & 32'd31));
  wire [31:0] pe8_325 = (pe2_71 >> (k_324 & 32'd31));
  wire [31:0] pe8_328 = (pe2_71 >> (k_323 & 32'd31));
  wire [31:0] pe6_329 = (pe2_71 ^ k_66);
  wire [31:0] pe8_337 = (pe2_71 >> (k_336 & 32'd31));
  wire [31:0] pe8_340 = (pe2_71 >> (k_335 & 32'd31));
  wire [31:0] pe6_341 = (pe2_71 ^ k_66);
  wire [31:0] pe8_348 = (pe2_71 >> (k_347 & 32'd31));
  wire [31:0] pe8_355 = (pe2_100 >> (k_354 & 32'd31));
  wire [31:0] pe8_358 = (pe2_100 >> (k_353 & 32'd31));
  wire [31:0] pe6_359 = (pe2_100 ^ k_66);
  wire [31:0] pe8_367 = (pe2_100 >> (k_366 & 32'd31));
  wire [31:0] pe8_370 = (pe2_100 >> (k_365 & 32'd31));
  wire [31:0] pe6_371 = (pe2_100 ^ k_66);
  wire [31:0] pe8_378 = (pe2_100 >> (k_377 & 32'd31));
  wire [31:0] pe8_385 = (pe2_110 >> (k_384 & 32'd31));
  wire [31:0] pe8_388 = (pe2_110 >> (k_383 & 32'd31));
  wire [31:0] pe6_389 = (pe2_110 ^ k_66);
  wire [31:0] pe8_397 = (pe2_110 >> (k_396 & 32'd31));
  wire [31:0] pe8_400 = (pe2_110 >> (k_395 & 32'd31));
  wire [31:0] pe6_401 = (pe2_110 ^ k_66);
  wire [31:0] pe8_408 = (pe2_110 >> (k_407 & 32'd31));
  wire and4_414 = lut4(16'h8000, {1'b1, src_en[1], not_413, xs2_1});
  wire [31:0] pe2_415 = (k_64 - th_1);
  wire [31:0] pe8_452 = (om_1 >> (k_65 & 32'd31));
  wire [31:0] pe1_458 = (om_1 + pe1_457);
  wire [31:0] pe1_460 = (qt_1 + k_65);
  wire [31:0] pe8_469 = (th_1 >> (k_468 & 32'd31));
  wire [31:0] pe8_479 = (pe2_81 >> (k_478 & 32'd31));
  wire [31:0] pe8_482 = (pe2_81 >> (k_477 & 32'd31));
  wire [31:0] pe6_483 = (pe2_81 ^ k_66);
  wire [31:0] pe8_491 = (pe2_81 >> (k_490 & 32'd31));
  wire [31:0] pe8_494 = (pe2_81 >> (k_489 & 32'd31));
  wire [31:0] pe6_495 = (pe2_81 ^ k_66);
  wire [31:0] pe8_502 = (pe2_81 >> (k_501 & 32'd31));
  wire [31:0] pe8_509 = (pe2_101 >> (k_508 & 32'd31));
  wire [31:0] pe8_512 = (pe2_101 >> (k_507 & 32'd31));
  wire [31:0] pe6_513 = (pe2_101 ^ k_66);
  wire [31:0] pe8_521 = (pe2_101 >> (k_520 & 32'd31));
  wire [31:0] pe8_524 = (pe2_101 >> (k_519 & 32'd31));
  wire [31:0] pe6_525 = (pe2_101 ^ k_66);
  wire [31:0] pe8_532 = (pe2_101 >> (k_531 & 32'd31));
  wire [31:0] pe8_539 = (pe2_120 >> (k_538 & 32'd31));
  wire [31:0] pe8_542 = (pe2_120 >> (k_537 & 32'd31));
  wire [31:0] pe6_543 = (pe2_120 ^ k_66);
  wire [31:0] pe8_551 = (pe2_120 >> (k_550 & 32'd31));
  wire [31:0] pe8_554 = (pe2_120 >> (k_549 & 32'd31));
  wire [31:0] pe6_555 = (pe2_120 ^ k_66);
  wire [31:0] pe8_562 = (pe2_120 >> (k_561 & 32'd31));
  wire and4_568 = lut4(16'h8000, {1'b1, src_en[2], not_567, xs2_2});
  wire [31:0] pe2_569 = (k_64 - th_2);
  wire [31:0] pe8_606 = (om_2 >> (k_65 & 32'd31));
  wire [31:0] pe1_612 = (om_2 + pe1_611);
  wire [31:0] pe1_614 = (qt_2 + k_65);
  wire [31:0] pe8_623 = (th_2 >> (k_622 & 32'd31));
  wire [31:0] pe8_633 = (pe2_91 >> (k_632 & 32'd31));
  wire [31:0] pe8_636 = (pe2_91 >> (k_631 & 32'd31));
  wire [31:0] pe6_637 = (pe2_91 ^ k_66);
  wire [31:0] pe8_645 = (pe2_91 >> (k_644 & 32'd31));
  wire [31:0] pe8_648 = (pe2_91 >> (k_643 & 32'd31));
  wire [31:0] pe6_649 = (pe2_91 ^ k_66);
  wire [31:0] pe8_656 = (pe2_91 >> (k_655 & 32'd31));
  wire [31:0] pe8_663 = (pe2_111 >> (k_662 & 32'd31));
  wire [31:0] pe8_666 = (pe2_111 >> (k_661 & 32'd31));
  wire [31:0] pe6_667 = (pe2_111 ^ k_66);
  wire [31:0] pe8_675 = (pe2_111 >> (k_674 & 32'd31));
  wire [31:0] pe8_678 = (pe2_111 >> (k_673 & 32'd31));
  wire [31:0] pe6_679 = (pe2_111 ^ k_66);
  wire [31:0] pe8_686 = (pe2_111 >> (k_685 & 32'd31));
  wire [31:0] pe8_693 = (pe2_121 >> (k_692 & 32'd31));
  wire [31:0] pe8_696 = (pe2_121 >> (k_691 & 32'd31));
  wire [31:0] pe6_697 = (pe2_121 ^ k_66);
  wire [31:0] pe8_705 = (pe2_121 >> (k_704 & 32'd31));
  wire [31:0] pe8_708 = (pe2_121 >> (k_703 & 32'd31));
  wire [31:0] pe6_709 = (pe2_121 ^ k_66);
  wire [31:0] pe8_716 = (pe2_121 >> (k_715 & 32'd31));
  wire and4_722 = lut4(16'h8000, {1'b1, src_en[3], not_721, xs2_3});
  wire [31:0] pe2_723 = (k_64 - th_3);
  wire [31:0] pe8_760 = (om_3 >> (k_65 & 32'd31));
  wire [31:0] pe1_766 = (om_3 + pe1_765);
  wire [31:0] pe1_768 = (qt_3 + k_65);
  wire [31:0] pe8_777 = (th_3 >> (k_776 & 32'd31));

  // level 2
  wire [31:0] bit_76 = (pe8_74 & k_75);
  wire [31:0] bit_86 = (pe8_84 & k_85);
  wire [31:0] bit_96 = (pe8_94 & k_95);
  wire [31:0] bit_106 = (pe8_104 & k_105);
  wire [31:0] bit_116 = (pe8_114 & k_115);
  wire [31:0] bit_126 = (pe8_124 & k_125);
  wire and_140 = lut4(16'h8888, {1'b0, 1'b0, not_139, or4_134});
  wire and_142 = lut4(16'h8888, {1'b0, 1'b0, src_en[0], eq_141});
  wire and_147 = lut4(16'h8888, {1'b0, 1'b0, not_146, or4_134});
  wire and_149 = lut4(16'h8888, {1'b0, 1'b0, src_en[1], eq_148});
  wire and_154 = lut4(16'h8888, {1'b0, 1'b0, not_153, or4_134});
  wire and_156 = lut4(16'h8888, {1'b0, 1'b0, src_en[2], eq_155});
  wire and_161 = lut4(16'h8888, {1'b0, 1'b0, not_160, or4_134});
  wire and_163 = lut4(16'h8888, {1'b0, 1'b0, src_en[3], eq_162});
  wire [31:0] bit_173 = (pe8_171 & k_172);
  wire [31:0] pe8_176 = (pe6_175 >> (k_169 & 32'd31));
  wire [31:0] bit_185 = (pe8_183 & k_184);
  wire [31:0] pe8_188 = (pe6_187 >> (k_181 & 32'd31));
  wire [31:0] bit_196 = (pe8_194 & k_195);
  wire [31:0] bit_203 = (pe8_201 & k_202);
  wire [31:0] pe8_206 = (pe6_205 >> (k_199 & 32'd31));
  wire [31:0] bit_215 = (pe8_213 & k_214);
  wire [31:0] pe8_218 = (pe6_217 >> (k_211 & 32'd31));
  wire [31:0] bit_226 = (pe8_224 & k_225);
  wire [31:0] bit_233 = (pe8_231 & k_232);
  wire [31:0] pe8_236 = (pe6_235 >> (k_229 & 32'd31));
  wire [31:0] bit_245 = (pe8_243 & k_244);
  wire [31:0] pe8_248 = (pe6_247 >> (k_241 & 32'd31));
  wire [31:0] bit_256 = (pe8_254 & k_255);
  wire [31:0] pe8_263 = (pe2_261 >> (k_262 & 32'd31));
  wire [31:0] pe2_266 = (k_64 - pe2_261);
  wire [31:0] pe8_278 = (pe2_261 >> (k_277 & 32'd31));
  wire [31:0] pe8_281 = (pe2_261 >> (k_276 & 32'd31));
  wire [31:0] pe6_282 = (pe2_261 ^ k_66);
  wire [31:0] pe8_289 = (pe2_261 >> (k_288 & 32'd31));
  wire [31:0] pe8_292 = (pe2_261 >> (k_287 & 32'd31));
  wire [31:0] pe6_293 = (pe2_261 ^ k_66);
  wire [31:0] sel_299 = (sl_0 ? pe8_298 : om_0);
  wire [31:0] sel_305 = (omega_we ? omega_d : pe1_304);
  wire [31:0] pe9_307 = ((pe1_306 < k_69) ? pe1_306 : k_69);
  wire [31:0] bit_317 = (pe8_315 & k_316);
  wire [31:0] bit_327 = (pe8_325 & k_326);
  wire [31:0] pe8_330 = (pe6_329 >> (k_323 & 32'd31));
  wire [31:0] bit_339 = (pe8_337 & k_338);
  wire [31:0] pe8_342 = (pe6_341 >> (k_335 & 32'd31));
  wire [31:0] bit_350 = (pe8_348 & k_349);
  wire [31:0] bit_357 = (pe8_355 & k_356);
  wire [31:0] pe8_360 = (pe6_359 >> (k_353 & 32'd31));
  wire [31:0] bit_369 = (pe8_367 & k_368);
  wire [31:0] pe8_372 = (pe6_371 >> (k_365 & 32'd31));
  wire [31:0] bit_380 = (pe8_378 & k_379);
  wire [31:0] bit_387 = (pe8_385 & k_386);
  wire [31:0] pe8_390 = (pe6_389 >> (k_383 & 32'd31));
  wire [31:0] bit_399 = (pe8_397 & k_398);
  wire [31:0] pe8_402 = (pe6_401 >> (k_395 & 32'd31));
  wire [31:0] bit_410 = (pe8_408 & k_409);
  wire [31:0] pe8_417 = (pe2_415 >> (k_416 & 32'd31));
  wire [31:0] pe2_420 = (k_64 - pe2_415);
  wire [31:0] pe8_432 = (pe2_415 >> (k_431 & 32'd31));
  wire [31:0] pe8_435 = (pe2_415 >> (k_430 & 32'd31));
  wire [31:0] pe6_436 = (pe2_415 ^ k_66);
  wire [31:0] pe8_443 = (pe2_415 >> (k_442 & 32'd31));
  wire [31:0] pe8_446 = (pe2_415 >> (k_441 & 32'd31));
  wire [31:0] pe6_447 = (pe2_415 ^ k_66);
  wire [31:0] sel_453 = (sl_1 ? pe8_452 : om_1);
  wire [31:0] sel_459 = (omega_we ? omega_d : pe1_458);
  wire [31:0] pe9_461 = ((pe1_460 < k_69) ? pe1_460 : k_69);
  wire [31:0] bit_471 = (pe8_469 & k_470);
  wire [31:0] bit_481 = (pe8_479 & k_480);
  wire [31:0] pe8_484 = (pe6_483 >> (k_477 & 32'd31));
  wire [31:0] bit_493 = (pe8_491 & k_492);
  wire [31:0] pe8_496 = (pe6_495 >> (k_489 & 32'd31));
  wire [31:0] bit_504 = (pe8_502 & k_503);
  wire [31:0] bit_511 = (pe8_509 & k_510);
  wire [31:0] pe8_514 = (pe6_513 >> (k_507 & 32'd31));
  wire [31:0] bit_523 = (pe8_521 & k_522);
  wire [31:0] pe8_526 = (pe6_525 >> (k_519 & 32'd31));
  wire [31:0] bit_534 = (pe8_532 & k_533);
  wire [31:0] bit_541 = (pe8_539 & k_540);
  wire [31:0] pe8_544 = (pe6_543 >> (k_537 & 32'd31));
  wire [31:0] bit_553 = (pe8_551 & k_552);
  wire [31:0] pe8_556 = (pe6_555 >> (k_549 & 32'd31));
  wire [31:0] bit_564 = (pe8_562 & k_563);
  wire [31:0] pe8_571 = (pe2_569 >> (k_570 & 32'd31));
  wire [31:0] pe2_574 = (k_64 - pe2_569);
  wire [31:0] pe8_586 = (pe2_569 >> (k_585 & 32'd31));
  wire [31:0] pe8_589 = (pe2_569 >> (k_584 & 32'd31));
  wire [31:0] pe6_590 = (pe2_569 ^ k_66);
  wire [31:0] pe8_597 = (pe2_569 >> (k_596 & 32'd31));
  wire [31:0] pe8_600 = (pe2_569 >> (k_595 & 32'd31));
  wire [31:0] pe6_601 = (pe2_569 ^ k_66);
  wire [31:0] sel_607 = (sl_2 ? pe8_606 : om_2);
  wire [31:0] sel_613 = (omega_we ? omega_d : pe1_612);
  wire [31:0] pe9_615 = ((pe1_614 < k_69) ? pe1_614 : k_69);
  wire [31:0] bit_625 = (pe8_623 & k_624);
  wire [31:0] bit_635 = (pe8_633 & k_634);
  wire [31:0] pe8_638 = (pe6_637 >> (k_631 & 32'd31));
  wire [31:0] bit_647 = (pe8_645 & k_646);
  wire [31:0] pe8_650 = (pe6_649 >> (k_643 & 32'd31));
  wire [31:0] bit_658 = (pe8_656 & k_657);
  wire [31:0] bit_665 = (pe8_663 & k_664);
  wire [31:0] pe8_668 = (pe6_667 >> (k_661 & 32'd31));
  wire [31:0] bit_677 = (pe8_675 & k_676);
  wire [31:0] pe8_680 = (pe6_679 >> (k_673 & 32'd31));
  wire [31:0] bit_688 = (pe8_686 & k_687);
  wire [31:0] bit_695 = (pe8_693 & k_694);
  wire [31:0] pe8_698 = (pe6_697 >> (k_691 & 32'd31));
  wire [31:0] bit_707 = (pe8_705 & k_706);
  wire [31:0] pe8_710 = (pe6_709 >> (k_703 & 32'd31));
  wire [31:0] bit_718 = (pe8_716 & k_717);
  wire [31:0] pe8_725 = (pe2_723 >> (k_724 & 32'd31));
  wire [31:0] pe2_728 = (k_64 - pe2_723);
  wire [31:0] pe8_740 = (pe2_723 >> (k_739 & 32'd31));
  wire [31:0] pe8_743 = (pe2_723 >> (k_738 & 32'd31));
  wire [31:0] pe6_744 = (pe2_723 ^ k_66);
  wire [31:0] pe8_751 = (pe2_723 >> (k_750 & 32'd31));
  wire [31:0] pe8_754 = (pe2_723 >> (k_749 & 32'd31));
  wire [31:0] pe6_755 = (pe2_723 ^ k_66);
  wire [31:0] sel_761 = (sl_3 ? pe8_760 : om_3);
  wire [31:0] sel_767 = (omega_we ? omega_d : pe1_766);
  wire [31:0] pe9_769 = ((pe1_768 < k_69) ? pe1_768 : k_69);
  wire [31:0] bit_779 = (pe8_777 & k_778);

  // level 3
  wire [31:0] sel_78 = (bit_76[0] ? pe2_77 : pe2_70);
  wire [31:0] sel_88 = (bit_86[0] ? pe2_87 : pe2_80);
  wire [31:0] sel_98 = (bit_96[0] ? pe2_97 : pe2_90);
  wire [31:0] sel_108 = (bit_106[0] ? pe2_107 : pe2_100);
  wire [31:0] sel_118 = (bit_116[0] ? pe2_117 : pe2_110);
  wire [31:0] sel_128 = (bit_126[0] ? pe2_127 : pe2_120);
  wire not_143 = lut4(16'h5555, {1'b0, 1'b0, 1'b0, and_142});
  wire not_150 = lut4(16'h5555, {1'b0, 1'b0, 1'b0, and_149});
  wire not_157 = lut4(16'h5555, {1'b0, 1'b0, 1'b0, and_156});
  wire not_164 = lut4(16'h5555, {1'b0, 1'b0, 1'b0, and_163});
  wire [31:0] pe6_177 = (pe8_176 ^ k_66);
  wire [31:0] pe6_189 = (pe8_188 ^ k_66);
  wire and_198 = lut4(16'h8888, {1'b0, 1'b0, not_197, bit_196[0]});
  wire [31:0] pe6_207 = (pe8_206 ^ k_66);
  wire [31:0] pe6_219 = (pe8_218 ^ k_66);
  wire and_228 = lut4(16'h8888, {1'b0, 1'b0, not_227, bit_226[0]});
  wire [31:0] pe6_237 = (pe8_236 ^ k_66);
  wire [31:0] pe6_249 = (pe8_248 ^ k_66);
  wire and_258 = lut4(16'h8888, {1'b0, 1'b0, not_257, bit_256[0]});
  wire [31:0] bit_265 = (pe8_263 & k_264);
  wire [31:0] bit_280 = (pe8_278 & k_279);
  wire [31:0] pe8_283 = (pe6_282 >> (k_276 & 32'd31));
  wire [31:0] bit_291 = (pe8_289 & k_290);
  wire [31:0] pe8_294 = (pe6_293 >> (k_287 & 32'd31));
  wire [31:0] pe1_300 = (th_0 + sel_299);
  wire not_309 = lut4(16'h5555, {1'b0, 1'b0, 1'b0, and_142});
  wire not_318 = lut4(16'h5555, {1'b0, 1'b0, 1'b0, bit_317[0]});
  wire [31:0] pe6_331 = (pe8_330 ^ k_66);
  wire [31:0] pe6_343 = (pe8_342 ^ k_66);
  wire and_352 = lut4(16'h8888, {1'b0, 1'b0, not_351, bit_350[0]});
  wire [31:0] pe6_361 = (pe8_360 ^ k_66);
  wire [31:0] pe6_373 = (pe8_372 ^ k_66);
  wire and_382 = lut4(16'h8888, {1'b0, 1'b0, not_381, bit_380[0]});
  wire [31:0] pe6_391 = (pe8_390 ^ k_66);
  wire [31:0] pe6_403 = (pe8_402 ^ k_66);
  wire and_412 = lut4(16'h8888, {1'b0, 1'b0, not_411, bit_410[0]});
  wire [31:0] bit_419 = (pe8_417 & k_418);
  wire [31:0] bit_434 = (pe8_432 & k_433);
  wire [31:0] pe8_437 = (pe6_436 >> (k_430 & 32'd31));
  wire [31:0] bit_445 = (pe8_443 & k_444);
  wire [31:0] pe8_448 = (pe6_447 >> (k_441 & 32'd31));
  wire [31:0] pe1_454 = (th_1 + sel_453);
  wire not_463 = lut4(16'h5555, {1'b0, 1'b0, 1'b0, and_149});
  wire not_472 = lut4(16'h5555, {1'b0, 1'b0, 1'b0, bit_471[0]});
  wire [31:0] pe6_485 = (pe8_484 ^ k_66);
  wire [31:0] pe6_497 = (pe8_496 ^ k_66);
  wire and_506 = lut4(16'h8888, {1'b0, 1'b0, not_505, bit_504[0]});
  wire [31:0] pe6_515 = (pe8_514 ^ k_66);
  wire [31:0] pe6_527 = (pe8_526 ^ k_66);
  wire and_536 = lut4(16'h8888, {1'b0, 1'b0, not_535, bit_534[0]});
  wire [31:0] pe6_545 = (pe8_544 ^ k_66);
  wire [31:0] pe6_557 = (pe8_556 ^ k_66);
  wire and_566 = lut4(16'h8888, {1'b0, 1'b0, not_565, bit_564[0]});
  wire [31:0] bit_573 = (pe8_571 & k_572);
  wire [31:0] bit_588 = (pe8_586 & k_587);
  wire [31:0] pe8_591 = (pe6_590 >> (k_584 & 32'd31));
  wire [31:0] bit_599 = (pe8_597 & k_598);
  wire [31:0] pe8_602 = (pe6_601 >> (k_595 & 32'd31));
  wire [31:0] pe1_608 = (th_2 + sel_607);
  wire not_617 = lut4(16'h5555, {1'b0, 1'b0, 1'b0, and_156});
  wire not_626 = lut4(16'h5555, {1'b0, 1'b0, 1'b0, bit_625[0]});
  wire [31:0] pe6_639 = (pe8_638 ^ k_66);
  wire [31:0] pe6_651 = (pe8_650 ^ k_66);
  wire and_660 = lut4(16'h8888, {1'b0, 1'b0, not_659, bit_658[0]});
  wire [31:0] pe6_669 = (pe8_668 ^ k_66);
  wire [31:0] pe6_681 = (pe8_680 ^ k_66);
  wire and_690 = lut4(16'h8888, {1'b0, 1'b0, not_689, bit_688[0]});
  wire [31:0] pe6_699 = (pe8_698 ^ k_66);
  wire [31:0] pe6_711 = (pe8_710 ^ k_66);
  wire and_720 = lut4(16'h8888, {1'b0, 1'b0, not_719, bit_718[0]});
  wire [31:0] bit_727 = (pe8_725 & k_726);
  wire [31:0] bit_742 = (pe8_740 & k_741);
  wire [31:0] pe8_745 = (pe6_744 >> (k_738 & 32'd31));
  wire [31:0] bit_753 = (pe8_751 & k_752);
  wire [31:0] pe8_756 = (pe6_755 >> (k_749 & 32'd31));
  wire [31:0] pe1_762 = (th_3 + sel_761);
  wire not_771 = lut4(16'h5555, {1'b0, 1'b0, 1'b0, and_163});
  wire not_780 = lut4(16'h5555, {1'b0, 1'b0, 1'b0, bit_779[0]});
  wire rom_782 = lut4(16'h22A2, {and_161, and_154, and_147, and_140});
  wire rom_783 = lut4(16'h0888, {and_161, and_154, and_147, and_140});
  wire rom_784 = lut4(16'h8000, {and_161, and_154, and_147, and_140});
  wire or4_795 = lut4(16'hFFFE, {and_163, and_156, and_149, and_142});
  wire or4_796 = lut4(16'hFFFE, {and_161, and_154, and_147, and_140});

  // level 4
  wire ltu_79 = (sel_78 < k_67);
  wire ltu_89 = (sel_88 < k_67);
  wire ltu_99 = (sel_98 < k_67);
  wire ltu_109 = (sel_108 < k_67);
  wire ltu_119 = (sel_118 < k_67);
  wire ltu_129 = (sel_128 < k_67);
  wire and4_144 = lut4(16'h8000, {1'b1, not_143, lk_0, src_en[0]});
  wire and4_151 = lut4(16'h8000, {1'b1, not_150, lk_1, src_en[1]});
  wire and4_158 = lut4(16'h8000, {1'b1, not_157, lk_2, src_en[2]});
  wire and4_165 = lut4(16'h8000, {1'b1, not_164, lk_3, src_en[3]});
  wire [31:0] sel_178 = (bit_173[0] ? pe6_177 : pe8_174);
  wire [31:0] sel_190 = (bit_185[0] ? pe6_189 : pe8_186);
  wire [31:0] sel_208 = (bit_203[0] ? pe6_207 : pe8_204);
  wire [31:0] sel_220 = (bit_215[0] ? pe6_219 : pe8_216);
  wire [31:0] sel_238 = (bit_233[0] ? pe6_237 : pe8_234);
  wire [31:0] sel_250 = (bit_245[0] ? pe6_249 : pe8_246);
  wire [31:0] sel_267 = (bit_265[0] ? pe2_266 : pe2_261);
  wire [31:0] pe6_284 = (pe8_283 ^ k_66);
  wire [31:0] pe6_295 = (pe8_294 ^ k_66);
  wire [31:0] pe1_302 = (pe1_300 + pe1_301);
  wire and_319 = lut4(16'h8888, {1'b0, 1'b0, not_318, hi_0[0]});
  wire [31:0] sel_332 = (bit_327[0] ? pe6_331 : pe8_328);
  wire [31:0] sel_344 = (bit_339[0] ? pe6_343 : pe8_340);
  wire [31:0] sel_362 = (bit_357[0] ? pe6_361 : pe8_358);
  wire [31:0] sel_374 = (bit_369[0] ? pe6_373 : pe8_370);
  wire [31:0] sel_392 = (bit_387[0] ? pe6_391 : pe8_388);
  wire [31:0] sel_404 = (bit_399[0] ? pe6_403 : pe8_400);
  wire [31:0] sel_421 = (bit_419[0] ? pe2_420 : pe2_415);
  wire [31:0] pe6_438 = (pe8_437 ^ k_66);
  wire [31:0] pe6_449 = (pe8_448 ^ k_66);
  wire [31:0] pe1_456 = (pe1_454 + pe1_455);
  wire and_473 = lut4(16'h8888, {1'b0, 1'b0, not_472, hi_1[0]});
  wire [31:0] sel_486 = (bit_481[0] ? pe6_485 : pe8_482);
  wire [31:0] sel_498 = (bit_493[0] ? pe6_497 : pe8_494);
  wire [31:0] sel_516 = (bit_511[0] ? pe6_515 : pe8_512);
  wire [31:0] sel_528 = (bit_523[0] ? pe6_527 : pe8_524);
  wire [31:0] sel_546 = (bit_541[0] ? pe6_545 : pe8_542);
  wire [31:0] sel_558 = (bit_553[0] ? pe6_557 : pe8_554);
  wire [31:0] sel_575 = (bit_573[0] ? pe2_574 : pe2_569);
  wire [31:0] pe6_592 = (pe8_591 ^ k_66);
  wire [31:0] pe6_603 = (pe8_602 ^ k_66);
  wire [31:0] pe1_610 = (pe1_608 + pe1_609);
  wire and_627 = lut4(16'h8888, {1'b0, 1'b0, not_626, hi_2[0]});
  wire [31:0] sel_640 = (bit_635[0] ? pe6_639 : pe8_636);
  wire [31:0] sel_652 = (bit_647[0] ? pe6_651 : pe8_648);
  wire [31:0] sel_670 = (bit_665[0] ? pe6_669 : pe8_666);
  wire [31:0] sel_682 = (bit_677[0] ? pe6_681 : pe8_678);
  wire [31:0] sel_700 = (bit_695[0] ? pe6_699 : pe8_696);
  wire [31:0] sel_712 = (bit_707[0] ? pe6_711 : pe8_708);
  wire [31:0] sel_729 = (bit_727[0] ? pe2_728 : pe2_723);
  wire [31:0] pe6_746 = (pe8_745 ^ k_66);
  wire [31:0] pe6_757 = (pe8_756 ^ k_66);
  wire [31:0] pe1_764 = (pe1_762 + pe1_763);
  wire and_781 = lut4(16'h8888, {1'b0, 1'b0, not_780, hi_3[0]});
  wire strobe_dec_785 = lut4(16'h0101, {1'b0, rom_784, rom_783, rom_782});
  wire strobe_dec_787 = lut4(16'h0202, {1'b0, rom_784, rom_783, rom_782});
  wire strobe_dec_789 = lut4(16'h0404, {1'b0, rom_784, rom_783, rom_782});
  wire strobe_dec_791 = lut4(16'h0808, {1'b0, rom_784, rom_783, rom_782});

  // level 5
  wire rom_166 = lut4(16'h0055, {and4_144, and_161, and_154, and_147});
  wire rom_167 = lut4(16'h0033, {and4_144, and_161, and_154, and_147});
  wire rom_168 = lut4(16'h000F, {and4_144, and_161, and_154, and_147});
  wire ltu_268 = (sel_267 < k_68);
  wire not_274 = lut4(16'h5555, {1'b0, 1'b0, 1'b0, and4_144});
  wire [31:0] sel_285 = (bit_280[0] ? pe6_284 : pe8_281);
  wire [31:0] sel_296 = (bit_291[0] ? pe6_295 : pe8_292);
  wire ltu_310 = (sel_267 < k_67);
  wire rom_320 = lut4(16'h0055, {and4_151, and_161, and_154, and_140});
  wire rom_321 = lut4(16'h0033, {and4_151, and_161, and_154, and_140});
  wire rom_322 = lut4(16'h000F, {and4_151, and_161, and_154, and_140});
  wire ltu_422 = (sel_421 < k_68);
  wire not_428 = lut4(16'h5555, {1'b0, 1'b0, 1'b0, and4_151});
  wire [31:0] sel_439 = (bit_434[0] ? pe6_438 : pe8_435);
  wire [31:0] sel_450 = (bit_445[0] ? pe6_449 : pe8_446);
  wire ltu_464 = (sel_421 < k_67);
  wire rom_474 = lut4(16'h0055, {and4_158, and_161, and_147, and_140});
  wire rom_475 = lut4(16'h0033, {and4_158, and_161, and_147, and_140});
  wire rom_476 = lut4(16'h000F, {and4_158, and_161, and_147, and_140});
  wire ltu_576 = (sel_575 < k_68);
  wire not_582 = lut4(16'h5555, {1'b0, 1'b0, 1'b0, and4_158});
  wire [31:0] sel_593 = (bit_588[0] ? pe6_592 : pe8_589);
  wire [31:0] sel_604 = (bit_599[0] ? pe6_603 : pe8_600);
  wire ltu_618 = (sel_575 < k_67);
  wire rom_628 = lut4(16'h0055, {and4_165, and_154, and_147, and_140});
  wire rom_629 = lut4(16'h0033, {and4_165, and_154, and_147, and_140});
  wire rom_630 = lut4(16'h000F, {and4_165, and_154, and_147, and_140});
  wire ltu_730 = (sel_729 < k_68);
  wire not_736 = lut4(16'h5555, {1'b0, 1'b0, 1'b0, and4_165});
  wire [31:0] sel_747 = (bit_742[0] ? pe6_746 : pe8_743);
  wire [31:0] sel_758 = (bit_753[0] ? pe6_757 : pe8_754);
  wire ltu_772 = (sel_729 < k_67);
  wire and_786 = lut4(16'h8888, {1'b0, 1'b0, strobe_dec_785, and_319});
  wire and_788 = lut4(16'h8888, {1'b0, 1'b0, strobe_dec_787, and_473});
  wire and_790 = lut4(16'h8888, {1'b0, 1'b0, strobe_dec_789, and_627});
  wire and_792 = lut4(16'h8888, {1'b0, 1'b0, strobe_dec_791, and_781});

  // level 6
  wire [31:0] sel_179 = (rom_166 ? sel_178 : k_64);
  wire [31:0] sel_191 = (rom_166 ? sel_190 : k_64);
  wire [31:0] sel_209 = (rom_167 ? sel_208 : k_64);
  wire [31:0] sel_221 = (rom_167 ? sel_220 : k_64);
  wire [31:0] sel_239 = (rom_168 ? sel_238 : k_64);
  wire [31:0] sel_251 = (rom_168 ? sel_250 : k_64);
  wire or_270 = lut4(16'hEEEE, {1'b0, 1'b0, ltu_268, not_269});
  wire not_272 = lut4(16'h5555, {1'b0, 1'b0, 1'b0, ltu_268});
  wire and4_275 = lut4(16'h8000, {not_274, and_258, and_228, and_198});
  wire or_311 = lut4(16'hEEEE, {1'b0, 1'b0, ltu_310, lk_0});
  wire [31:0] sel_333 = (rom_320 ? sel_332 : k_64);
  wire [31:0] sel_345 = (rom_320 ? sel_344 : k_64);
  wire [31:0] sel_363 = (rom_321 ? sel_362 : k_64);
  wire [31:0] sel_375 = (rom_321 ? sel_374 : k_64);
  wire [31:0] sel_393 = (rom_322 ? sel_392 : k_64);
  wire [31:0] sel_405 = (rom_322 ? sel_404 : k_64);
  wire or_424 = lut4(16'hEEEE, {1'b0, 1'b0, ltu_422, not_423});
  wire not_426 = lut4(16'h5555, {1'b0, 1'b0, 1'b0, ltu_422});
  wire and4_429 = lut4(16'h8000, {not_428, and_412, and_382, and_352});
  wire or_465 = lut4(16'hEEEE, {1'b0, 1'b0, ltu_464, lk_1});
  wire [31:0] sel_487 = (rom_474 ? sel_486 : k_64);
  wire [31:0] sel_499 = (rom_474 ? sel_498 : k_64);
  wire [31:0] sel_517 = (rom_475 ? sel_516 : k_64);
  wire [31:0] sel_529 = (rom_475 ? sel_528 : k_64);
  wire [31:0] sel_547 = (rom_476 ? sel_546 : k_64);
  wire [31:0] sel_559 = (rom_476 ? sel_558 : k_64);
  wire or_578 = lut4(16'hEEEE, {1'b0, 1'b0, ltu_576, not_577});
  wire not_580 = lut4(16'h5555, {1'b0, 1'b0, 1'b0, ltu_576});
  wire and4_583 = lut4(16'h8000, {not_582, and_566, and_536, and_506});
  wire or_619 = lut4(16'hEEEE, {1'b0, 1'b0, ltu_618, lk_2});
  wire [31:0] sel_641 = (rom_628 ? sel_640 : k_64);
  wire [31:0] sel_653 = (rom_628 ? sel_652 : k_64);
  wire [31:0] sel_671 = (rom_629 ? sel_670 : k_64);
  wire [31:0] sel_683 = (rom_629 ? sel_682 : k_64);
  wire [31:0] sel_701 = (rom_630 ? sel_700 : k_64);
  wire [31:0] sel_713 = (rom_630 ? sel_712 : k_64);
  wire or_732 = lut4(16'hEEEE, {1'b0, 1'b0, ltu_730, not_731});
  wire not_734 = lut4(16'h5555, {1'b0, 1'b0, 1'b0, ltu_730});
  wire and4_737 = lut4(16'h8000, {not_736, and_720, and_690, and_660});
  wire or_773 = lut4(16'hEEEE, {1'b0, 1'b0, ltu_772, lk_3});
  wire or4_793 = lut4(16'hFFFE, {and_792, and_790, and_788, and_786});

  // level 7
  wire [31:0] pe1_180 = (k_64 + sel_179);
  wire [31:0] pe1_192 = (k_64 + sel_191);
  wire and_271 = lut4(16'h8888, {1'b0, 1'b0, or_270, and4_260});
  wire and4_273 = lut4(16'h8000, {1'b1, not_272, lk_0, and4_260});
  wire [31:0] pe1_334 = (k_64 + sel_333);
  wire [31:0] pe1_346 = (k_64 + sel_345);
  wire and_425 = lut4(16'h8888, {1'b0, 1'b0, or_424, and4_414});
  wire and4_427 = lut4(16'h8000, {1'b1, not_426, lk_1, and4_414});
  wire [31:0] pe1_488 = (k_64 + sel_487);
  wire [31:0] pe1_500 = (k_64 + sel_499);
  wire and_579 = lut4(16'h8888, {1'b0, 1'b0, or_578, and4_568});
  wire and4_581 = lut4(16'h8000, {1'b1, not_580, lk_2, and4_568});
  wire [31:0] pe1_642 = (k_64 + sel_641);
  wire [31:0] pe1_654 = (k_64 + sel_653);
  wire and_733 = lut4(16'h8888, {1'b0, 1'b0, or_732, and4_722});
  wire and4_735 = lut4(16'h8000, {1'b1, not_734, lk_3, and4_722});
  wire and_794 = lut4(16'h8888, {1'b0, 1'b0, or4_793, or4_134});

  // level 8
  wire [31:0] pe1_210 = (pe1_180 + sel_209);
  wire [31:0] pe1_222 = (pe1_192 + sel_221);
  wire [31:0] sel_286 = (and_271 ? sel_285 : k_64);
  wire [31:0] sel_297 = (and_271 ? sel_296 : k_64);
  wire [31:0] sel_308 = (and_271 ? k_64 : pe9_307);
  wire mux_312 = lut4(16'hE4E4, {1'b0, or_311, lk_0, and_271});
  wire [31:0] pe1_364 = (pe1_334 + sel_363);
  wire [31:0] pe1_376 = (pe1_346 + sel_375);
  wire [31:0] sel_440 = (and_425 ? sel_439 : k_64);
  wire [31:0] sel_451 = (and_425 ? sel_450 : k_64);
  wire [31:0] sel_462 = (and_425 ? k_64 : pe9_461);
  wire mux_466 = lut4(16'hE4E4, {1'b0, or_465, lk_1, and_425});
  wire [31:0] pe1_518 = (pe1_488 + sel_517);
  wire [31:0] pe1_530 = (pe1_500 + sel_529);
  wire [31:0] sel_594 = (and_579 ? sel_593 : k_64);
  wire [31:0] sel_605 = (and_579 ? sel_604 : k_64);
  wire [31:0] sel_616 = (and_579 ? k_64 : pe9_615);
  wire mux_620 = lut4(16'hE4E4, {1'b0, or_619, lk_2, and_579});
  wire [31:0] pe1_672 = (pe1_642 + sel_671);
  wire [31:0] pe1_684 = (pe1_654 + sel_683);
  wire [31:0] sel_748 = (and_733 ? sel_747 : k_64);
  wire [31:0] sel_759 = (and_733 ? sel_758 : k_64);
  wire [31:0] sel_770 = (and_733 ? k_64 : pe9_769);
  wire mux_774 = lut4(16'hE4E4, {1'b0, or_773, lk_3, and_733});

  // level 9
  wire [31:0] pe1_240 = (pe1_210 + sel_239);
  wire [31:0] pe1_252 = (pe1_222 + sel_251);
  wire and_313 = lut4(16'h8888, {1'b0, 1'b0, mux_312, not_309});
  wire [31:0] pe1_394 = (pe1_364 + sel_393);
  wire [31:0] pe1_406 = (pe1_376 + sel_405);
  wire and_467 = lut4(16'h8888, {1'b0, 1'b0, mux_466, not_463});
  wire [31:0] pe1_548 = (pe1_518 + sel_547);
  wire [31:0] pe1_560 = (pe1_530 + sel_559);
  wire and_621 = lut4(16'h8888, {1'b0, 1'b0, mux_620, not_617});
  wire [31:0] pe1_702 = (pe1_672 + sel_701);
  wire [31:0] pe1_714 = (pe1_684 + sel_713);
  wire and_775 = lut4(16'h8888, {1'b0, 1'b0, mux_774, not_771});

  always @(posedge clk) begin
    if (rst) begin
      xs1_0 <= 1'h0;
      xs2_0 <= 1'h0;
      xs3_0 <= 1'h0;
      hi_0 <= 32'h00000000;
      lk_0 <= 1'h0;
      th_0 <= 32'h00000000;
      om_0 <= 32'h10000000;
      qt_0 <= 32'h00000000;
      cp_0 <= 32'h00000000;
      ad_0 <= 32'h00000000;
      ij_0 <= 32'h00000000;
      fj_0 <= 32'h00000000;
      sl_0 <= 1'h0;
      xs1_1 <= 1'h0;
      xs2_1 <= 1'h0;
      xs3_1 <= 1'h0;
      hi_1 <= 32'h00000000;
      lk_1 <= 1'h0;
      th_1 <= 32'h50000000;
      om_1 <= 32'h10F5C28F;
      qt_1 <= 32'h00000000;
      cp_1 <= 32'h00000000;
      ad_1 <= 32'h00000000;
      ij_1 <= 32'h00000000;
      fj_1 <= 32'h00000000;
      sl_1 <= 1'h0;
      xs1_2 <= 1'h0;
      xs2_2 <= 1'h0;
      xs3_2 <= 1'h0;
      hi_2 <= 32'h00000000;
      lk_2 <= 1'h0;
      th_2 <= 32'hA0000000;
      om_2 <= 32'h0F333333;
      qt_2 <= 32'h00000000;
      cp_2 <= 32'h00000000;
      ad_2 <= 32'h00000000;
      ij_2 <= 32'h00000000;
      fj_2 <= 32'h00000000;
      sl_2 <= 1'h0;
      xs1_3 <= 1'h0;
      xs2_3 <= 1'h0;
      xs3_3 <= 1'h0;
      hi_3 <= 32'h00000000;
      lk_3 <= 1'h0;
      th_3 <= 32'hF0000000;
      om_3 <= 32'h107AE148;
      qt_3 <= 32'h00000000;
      cp_3 <= 32'h00000000;
      ad_3 <= 32'h00000000;
      ij_3 <= 32'h00000000;
      fj_3 <= 32'h00000000;
      sl_3 <= 1'h0;
      nq01 <= 1'h0;
      nq02 <= 1'h0;
      nq03 <= 1'h0;
      nq12 <= 1'h0;
      nq13 <= 1'h0;
      nq23 <= 1'h0;
      sta_0 <= 1'h0;
      sta_1 <= 1'h0;
      sta_2 <= 1'h0;
      sta_3 <= 1'h0;
    end else begin
      xs1_0 <= src0;
      xs2_0 <= n801;
      xs3_0 <= n802;
      hi_0 <= bit_317;
      lk_0 <= and_313;
      th_0 <= pe1_302;
      om_0 <= sel_305;
      qt_0 <= sel_308;
      cp_0 <= pe1_240;
      ad_0 <= pe1_252;
      ij_0 <= sel_286;
      fj_0 <= sel_297;
      sl_0 <= and4_275;
      xs1_1 <= src1;
      xs2_1 <= n803;
      xs3_1 <= n804;
      hi_1 <= bit_471;
      lk_1 <= and_467;
      th_1 <= pe1_456;
      om_1 <= sel_459;
      qt_1 <= sel_462;
      cp_1 <= pe1_394;
      ad_1 <= pe1_406;
      ij_1 <= sel_440;
      fj_1 <= sel_451;
      sl_1 <= and4_429;
      xs1_2 <= src2;
      xs2_2 <= n805;
      xs3_2 <= n806;
      hi_2 <= bit_625;
      lk_2 <= and_621;
      th_2 <= pe1_610;
      om_2 <= sel_613;
      qt_2 <= sel_616;
      cp_2 <= pe1_548;
      ad_2 <= pe1_560;
      ij_2 <= sel_594;
      fj_2 <= sel_605;
      sl_2 <= and4_583;
      xs1_3 <= src3;
      xs2_3 <= n807;
      xs3_3 <= n808;
      hi_3 <= bit_779;
      lk_3 <= and_775;
      th_3 <= pe1_764;
      om_3 <= sel_767;
      qt_3 <= sel_770;
      cp_3 <= pe1_702;
      ad_3 <= pe1_714;
      ij_3 <= sel_748;
      fj_3 <= sel_759;
      sl_3 <= and4_737;
      nq01 <= ltu_79;
      nq02 <= ltu_89;
      nq03 <= ltu_99;
      nq12 <= ltu_109;
      nq13 <= ltu_119;
      nq23 <= ltu_129;
      sta_0 <= or4_134;
      sta_1 <= or4_795;
      sta_2 <= or4_796;
      sta_3 <= and_794;
    end
  end

  // outputs
  assign phase_out = th_0;
  assign freq_out = om_0;
  assign wrap = {and_781, and_627, and_473, and_319};
  assign near = {nq23, nq13, nq12, nq03, nq02, nq01};
  assign fault = {and_161, and_154, and_147, and_140};
  assign lost = {and_163, and_156, and_149, and_142};
  assign locked = {lk_3, lk_2, lk_1, lk_0};
  assign glitch = {and4_735, and4_581, and4_427, and4_273};
  assign coherent = and4_137;
  assign quorum = or4_134;
  assign ec_tick = and_794;
  assign status = {sta_3, sta_2, sta_1, sta_0};
endmodule
